### ISSUE TITLE
Pi zero 2 waits for root for ever after e6c1e862b2b8150a419f4208e5bd7749662b16a1

### ISSUE THREAD

**Issue by fishrockz** [raspberrypi/linux#6267] opened 2024-07-14 19:36 UTC
### Describe the bug

I updated the kernel in my pi images to the default commit from this repo, e6c1e862b2b8150a419f4208e5bd7749662b16a1 via https://github.com/raspberrypi/linux/commits/rpi-6.6.y/

See diff in my yoto like repo, https://gitlab.com/pointswaves/girderstream-test-project/-/commit/e9287efbb21b5a1fd824c312c7c90a526ab9c40b

When booting with  this change the kernel seems to wait for root for ever on the pi zero 2

The logs show the wait for root then the sdcard shows up with mmcblk0 as expected but the pi zero 2 does not continue the boot, my pi4 boots with the commit before and this commit.

I dont normally have a serial port setup but i can use that to capture the exact logs if needed.

### Steps to reproduce the behaviour

update to latest kernel

boot on pi zero 2

system waits for root file system for ever

I build my image in CI https://gitlab.com/pointswaves/girderstream-test-project/-/jobs/7338191672 and that saves the image here https://gitlab.com/pointswaves/girderstream-test-project/-/jobs/7338191672/artifacts/browse/filesystem-target/

### Device (s)

Raspberry Pi Zero 2 W

### System

custom os but the kernel does not get that far
vcgencmd is not installed
uname -a: 6.6.39-v8

### Logs

As you can see i have also updated the firmware, https://gitlab.com/pointswaves/girderstream-test-project/-/commit/e9287efbb21b5a1fd824c312c7c90a526ab9c40b

These are the only changes that cause this issue.. 

please note that 89f80b37bc78986a109897ada807213fbbfe91ad fixes the issue so i think https://github.com/raspberrypi/linux/commit/e6c1e862b2b8150a419f4208e5bd7749662b16a1 is causing the issue..

**Comment by pelwell** [comment] 2024-07-14 20:00
This is a good bug report, but it's a duplicate of https://github.com/raspberrypi/linux/issues/6266, so I'm going to close it to avoid splitting the commentary.

**Closed as completed by pelwell** 2024-07-14 20:00 UTC
