### ISSUE TITLE
kernel oops. 

### ISSUE THREAD

**Issue by rewolff** [raspberrypi/linux#31] opened 2012-06-02 20:19 UTC
Hi, 

While my 'pi was doing real work for me it crashed 15 minutes after I had left. :-( 

It produced the attached "ooops" (provided I can find how to attach files) . 

It's reading from an SD card (microSD to be exact), and writing the data over a TPC connection to a server. This is progressing at 300k/sec. (with 32G total, that is expected tot take 29 hours). 

It has now been running since this morning: about 14 hours.

**Comment by rewolff** [comment] 2012-06-02 20:20
I can't find how to attach files here, so I'll have to host the file myself: http://prive.bitwizard.nl/DSC04643.JPG

**Comment by rewolff** [comment] 2012-06-04 10:19
I checked my current copy of system.map. I did recompile the kernel adding a few modules, so I don't think the symbols moved, but I can't be sure. 

Crash occurred in memcpy (sounds reasonable). 
linkregister contains DWC_TASK_SCHEDULE (0xc before the end). (which as far as I can tell doesn't call memcpy).

**Comment by popcornmix** [comment] 2012-08-21 11:09
Can you reproduce this on latest 3.2.27 kernel?

**Comment by ghollingworth** [comment] 2012-09-13 19:12
Closing since there's been no further investigation

**Closed as completed by ghollingworth** 2012-09-13 19:12 UTC

**Comment by rewolff** [comment] 2012-09-14 07:01
Sounds like a plan. It was hard for me to reproduce. I was hoping the report might fit into a pattern or something like that.
