### ISSUE TITLE
Music playback using Meridian Explorer USB DAC has crackles

### ISSUE THREAD

**Issue by asktoby** [raspberrypi/linux#2339] opened 2018-01-12 10:48 UTC
When I playback audio using a Meridian Explorer USB DAC I get occasional crackles.

The attached screenshots are taken with a 100Hz sinewave playing.

This glitch appears as often as once every 6 seconds but not at regular intervals.
Looks like a pause in the stream of 2ms.

![skip](https://user-images.githubusercontent.com/129841/34871553-0752bc50-f786-11e7-9b6d-df4eb30073fd.jpg)
![clickgap](https://user-images.githubusercontent.com/129841/34871554-076f714c-f786-11e7-978f-40f59ff4cdcb.jpg)
Here's a different type of click, smaller, looks like it's skipped a few samples:
![clickgap2](https://user-images.githubusercontent.com/129841/34871556-078a9a26-f786-11e7-9a52-fd76fc6caa07.jpg)

The same crackles are heard if I use mpg123 in a fresh install of Raspbian, or if I use Moode Audio or Volumio forks of Raspbian, so it seems like there is an underlying problem with Raspbian playback.

Here is some system info:
https://pastebin.com/bN4kz4QM

If I change the USB DAC to another, a Soundblaster sb1290, then the crackles go away.

**Comment by pelwell** [comment] 2018-01-12 11:22
Duplicate of #2215. There is some hope that the glitching is due to a specific change in the handling of softirqs - Linus is aware and they are working on a fix.

**Closed as completed by pelwell** 2018-01-12 11:22 UTC

**Comment by Wang-Yue** [comment] 2019-01-31 19:02
@pelwell is there a official kernel bug that I can track?
