### ISSUE TITLE
IBSS (AdHoc) does not work on RPI 3B+ (and possibly others)

### ISSUE THREAD

**Issue by darkdrgn2k** [raspberrypi/linux#2629] opened 2018-07-28 23:16 UTC
Can't seem to configure pi into IBSS (AdHoc) mode 

```
$ sudo  iwconfig wlan0 mode ad-hoc essid my-mesh ap 02:12:34:56:78:9A channel 1
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Device or resource busy.
```

```
$ dmesg
brcmf_cfg80211_change_iface: iface validation failed: err=-16
```

Running Laters Raspbian and also rpi-update `4.14.56-v7+`

**Comment by popcornmix** [comment] 2018-07-31 11:34
Duplicate of https://github.com/raspberrypi/firmware/issues/990 ?

**Comment by darkdrgn2k** [comment] 2018-07-31 14:10
Could also be a re-surfacing of #1384

Not sure if its a Firmware issue or a Kernel Issue.

**Comment by popcornmix** [comment] 2018-07-31 14:12
It's not a (gpu) firmware issue (that has no knowledge of wifi).
I don't know enough to say if it's a kernel issue (possibly the wifi firmware) or a linux configuration issue.

**Comment by JamesH65** [comment] 2019-07-31 10:46
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by JamesH65** [comment] 2019-09-18 16:12
Closing due to lack of activity. Please request to be reopened if you feel this issue is still relevant.

**Closed as completed by JamesH65** 2019-09-18 16:12 UTC
Labels: Close within 30 days
