### ISSUE TITLE
add CONFIG_SQUASHFS_LZ4=y

### ISSUE THREAD

**Issue by monetny** [raspberrypi/linux#2194] opened 2017-09-10 00:20 UTC
I think add CONFIG_SQUASHFS_LZ4=y is good idea,
because stretch mksqashfs support it
and original kernel debian stretch include it option

**Comment by pelwell** [comment] 2017-09-14 14:00
Duplicate of https://github.com/raspberrypi/linux/issues/2006.

**Closed as completed by pelwell** 2017-09-14 14:00 UTC
