### ISSUE TITLE
Atari Retrobit USB adapter not working

### ISSUE THREAD

**Issue by JTCook** [raspberrypi/linux#432] opened 2013-11-13 05:46 UTC
The Atari retrobit USB adapter is not working. This device is essentially a dual USB controller where you can plug in two Atari joysticks. What happens when the device is plugged in, the OS will not recognize up or left on the controller (though right, down, and fire are functional). More details our outlined here:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=78&t=36564
this is the device: http://www.amazon.com/gp/product/B007ZS35CU/

I believe the issue appears to be how the kernel handles USB HID devices. I also believe this was an issue with older Linux builds, but most current ones have this item fixed.

**Comment by P33M** [comment] 2013-11-13 10:31
Use the command `showkeys` and see if anything is printed to the terminal when you push each button.

**Comment by JTCook** [comment] 2013-11-14 03:23
I tried showkey and it looks like it only works with the keyboard. However when I tried cat dev/input/js0 it would show output whenever I used up, down, right, and button one, but not up or left. I also tried with another USB joypad and all directions work as well has showing output whenever I hit all directions and buttons.

I have also tried the Atari USB adapter on an EEE PC netbook with Linux and it did recognize all the inputs correctly.

**Comment by P33M** [comment] 2013-11-14 11:20
Can you post a lsusb -v and dmesg from boot with the Atari adapter plugged in?

**Comment by JTCook** [comment] 2013-11-15 06:07
I have copied the output of lsusb and dmesg from both the Raspberry PI and Linux netbook for comparison. 
https://gist.github.com/JTCook/7479729

It looks like my USB device is a tad different, it calls itself the INNEX GENESIS Controller.

**Comment by P33M** [comment] 2013-11-15 08:52
The lsusb on the netbook is a dupe of the dmesg.

Other than that, your atari adapter plugged into the Pi appears to be a garden variety HID device.

**Comment by JTCook** [comment] 2013-11-17 04:45
Oops, I have corrected the lsusb file for the netbook. It is just more or less a basic HID joystick, except that the UP and LEFT inputs do not register. Apparently in older versions of Linux this is an issue as well.

**Comment by P33M** [comment] 2013-11-17 15:11
You are using 3.6.11 #371 which is nearly 9 months old.

Please test after using rpi-update to update to 3.10.y.

**Comment by JTCook** [comment] 2013-11-25 02:34
I ran rpi-update, rebooted the device, and the controller still has the same issue.

**Comment by sjvc** [comment] 2013-12-21 20:27
Same here. All buttons are working except left and up. Anybody can help us?

**Comment by JTCook** [comment] 2014-01-19 04:01
It looks like someone has solved this problem! The fix is located in the same thread where people have reported the problem. Can this fix now be incorporated into the build?
Fix: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=78&t=36564&p=487878&hilit=retrobit#p487878

**Comment by asb** [comment] 2014-01-19 11:34
I'm glad to hear a fix has been found, but this doesn't sound like a
pi-specific issue so should really be submitted upstream for review
and potential inclusion.

**Comment by P33M** [comment] 2014-05-07 15:43
Latest branch is 3.12. Quirks are likely to have been incorporated upstream.

**Closed as completed by P33M** 2014-05-07 15:43 UTC
