### ISSUE TITLE
Kernel headers for the latest Raspberry OS 5.4.50-v8+ arm64 is missing

### ISSUE THREAD

**Issue by JulyIghor** [raspberrypi/linux#3705] opened 2020-07-03 16:33 UTC
Why there is no kernel headers for latest kernel of Raspberry OS arm64 in the repo?
Can't install Wireguard or any kernel module.

**Comment by pelwell** [comment] 2020-07-03 16:42
Duplicate of https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/4.

**Closed as completed by pelwell** 2020-07-03 16:42 UTC
