### ISSUE TITLE
rpi-4.16.y doesn't boot - black screen, no output from serial, green leds are off, etc

### ISSUE THREAD

**Issue by piso77** [raspberrypi/linux#2432] opened 2018-03-12 08:58 UTC
Just compiled a new kernel from the above branch:

077ca8c usb: dwb_otg: Fix unreachable switch statement warning
81de073 staging: vchiq_arm: Remove unused variable
a97d0db sound: bcm: Fix memset dereference warning
...

using bcm2709_defconfig.

After a reboot, my raspberrypi3 is stuck with no output at all on the serial, green leds are off (after a brief activity), LAN is off too, etc

**Comment by pelwell** [comment] 2018-03-12 09:14
1. Is the kernel the only thing you changed since the last successful boot?
2. Which version of the kernel did you come from?
3. If you replace kernel7.img with another version does it boot? (This assumes the modules for the older kernel are still on the card)

**Comment by piso77** [comment] 2018-03-12 11:49
1) kernel and bcm2710-rpi-3-b.dtb

2) my working environment:

$ dpkg -l | grep raspberrypi-
ii  libraspberrypi-bin              1.20171029-1                 armhf        Miscellaneous Raspberry Pi utilities
ii  libraspberrypi-dev              1.20171029-1                 armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  libraspberrypi-doc              1.20171029-1                 armhf        EGL/GLES/OpenVG/etc. libraries for the Raspberry Pi's VideoCore IV (headers)
ii  raspberrypi-bootloader          1.20171029-1                 armhf        Raspberry Pi bootloader
ii  raspberrypi-kernel              1.20171029-1                 armhf        Raspberry Pi bootloader
ii  raspberrypi-net-mods            1.2.7                        all          Network configuration for the Raspberry Pi UI
ii  raspberrypi-sys-mods            20180103                     armhf        System tweaks for the Raspberry Pi

$ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

$ grep -Ev '^#|^$' /boot/config.txt 
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
enable_uart=1
dtdebug=1

and upon installation i did:

$ sudo cp /boot/kernel7.img /boot/kernel7.img.old
$ sudo cp /boot/bcm2710-rpi-3-b.dtb /boot/bcm2710-rpi-3-b.dtb.old
[cross-built the 4.16.y branch with bcm2709_defconfig, tarred up the result in 'upstream.tgz', copied over to rpi3 and decompressed]
$ sudo upstream/mkknlimg upstream/vmlinuz /boot/kernel7.img
$ sudo cp upstream//boot/bcm2710-rpi-3-b.dtb /boot/bcm2710-rpi-3-b.dtb.old
$ sudo cp -R upstream/lib/modules/4.16.0-rc4-v7+ /lib/modules/

FWIW i'm using a couple of scripts to build upstream, copy and install since i do it all the time with every raspy-4.X.y branch.

3) yes, i put it back the previous kernel7.img and bcm2710-rpi-3-b.dtb and i'm back to 4.9.59

Anything i can add to try get some output? earlycon? config.txt debug magic?

**Comment by pelwell** [comment] 2018-03-12 13:22
I can reproduce the problem. It's not high on the list of priorities at the moment since 4.16 is so new, but it will get looked at.

**Comment by pelwell** [comment] 2018-03-12 16:54
It's something to do with the FIQ support. Try disabling it in cmdline.txt:
```
... dwc_otg.fiq_enable=0 dwc_otg.fiq_fsm_enable=0
```

**Comment by piso77** [comment] 2018-03-12 17:35
Awesome, it boots now (though my console is spammed with 'raspberrypi-firmware soc:firmware: Request 0x00030046 returned status 0x80000001' messages).

Question: how did you debug it?

1) did you bisect your BSP until you found it was related to FIQ?

2) did you use some config.txt magic? or any other undisclosed debug mode?

3) did you JTAG the board?

**Comment by pelwell** [comment] 2018-03-12 19:00
I used JTAG to read the memory where the log is stored, noticed that the last message was USB-related, and guessed that FIQ may be involved. Then remembered that we had diagnosed (but not cured) a FIQ issue before on 4.16.

**Comment by pelwell** [comment] 2018-03-12 19:00
If you update the firmware those

**Comment by pelwell** [comment] 2018-03-12 19:03
If you update the firmware those messages will go away. They are caused by the new under-voltage, over-temperature polling service which requires a new mailbox method in the firmware.

**Comment by piso77** [comment] 2018-03-14 10:24
I see, i manually updated the firmware boot files and these messages disappeared.

I'll keep an eye on the rpi-4.16.y to see if anything lands about FIQ.

BTW, i found another problem with the dt overlay when removing an overlay (i get a nice stacktrace) - but i'm not sure you want to hear that here, i shall open a new issue, or we should just wait for 4.16 to stabilize.

**Comment by pelwell** [comment] 2018-03-14 10:28
Removing overlays can be hit-and-miss depending on the overlay and the drivers it pulls in, but if it's something that has worked on previous kernels then please do report it - in a separate issue - but understand that it may take a while to switch our focus to 4.16.

**Comment by nkichukov** [comment] 2018-04-02 20:37
Same here on rpi-4.16.0-rc7. 

Where the last working kernel was: 4.15.0-rc7. The suggested workaround fixes the problem and makes the USB devices work - sd card, usb keyboard, etc. Gentoo Linux.

Glad the search engine brought me here after recompiling the kernel  several times in vain.

**Comment by JamesH65** [comment] 2018-05-11 10:38
@pelwell @p33m Did the FIQ support get fixed? Can this be closed? Or are we still at the workaround level?

**Comment by pelwell** [comment] 2018-05-11 10:41
I've not looked at it beyond the initial "it's the FIQ" diagnosis.

**Comment by mkreisl** [comment] 2018-05-23 15:55
The issue still persists (4.16.10+)

And adding `dwc_otg.fiq_enable=0 dwc_otg.fiq_fsm_enable=0` to /boot/cmdlint.txt as workaround solves this temporarly 

And using dwc2 instead of dwc (adding `dtoverlay=dwc2,dr_mode=host` to /boot/config.txt) does not help (looks like that module is broken as well)
Edit: After including dwc2 module into initramfs, everything is ok. So issue is in dwc-otg module only

**Comment by lategoodbye** [comment] 2018-05-23 18:15
@mkreisl It's hard to believe that a dwc2 issue stops the Pi from booting to screen. I can't remember such an issue upstream.

So there is no debug UART output in your case? Also using a RPI 3?

**Comment by mkreisl** [comment] 2018-05-23 18:41
@lategoodbye 
You're right, was my mistake. Forgot to add dwc2 module into initramfs (my test configuration requires it because using iSCSI target as root fs), so network could not be initialized and boot process stucks. Can't remember what I did when testing dwc2 modules last time (approx 6 weeks ago)

And yes, using Pi3B+

**Comment by pelwell** [comment] 2018-06-14 13:29
This should be fixed now  - see https://github.com/raspberrypi/linux/commit/2362500e0a547b4683c86725aa0aa7b38cbbdbe1

**Comment by mkreisl** [comment] 2018-06-14 13:32
> This should be fixed now - see 2362500

Yep, can confirm, it does :smile: Thanks

**Comment by pelwell** [comment] 2018-06-14 13:35
Cherry-picked to rpi-4.17.y as 0043c8413f7b0466a378ebeb4083a9001a6ac354

**Comment by HiassofT** [comment] 2018-06-14 15:20
@pelwell I just wanted to say a huge "thank you", and pass over a virtual bottle of single malt.

I did a quick test with latest 4.17.1 on LibreELEC, it booted up fine and USB audio worked again!

**Comment by pelwell** [comment] 2018-06-14 15:26
Thanks, but I'll settle for reducing my debt to you a little.

**Comment by JamesH65** [comment] 2018-06-29 14:14
Closing this issue as questions answered/issue resolved.

**Closed as completed by JamesH65** 2018-06-29 14:14 UTC
Labels: Close within 30 days
