### ISSUE TITLE
LXC Support

### ISSUE THREAD

**Issue by bullshit** [raspberrypi/linux#572] opened 2014-04-21 19:08 UTC
Is it possible to include all necessary modules for linux container support?  (Support multiple instances of devpts) VETH was added in #550 . I successful compiled it on the last kernel updates in the 3.10.y branch. It would be nice if it is always on.. 

```
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
```

**Comment by popcornmix** [comment] 2014-06-29 18:47
Duplicate of https://github.com/raspberrypi/linux/pull/603

**Closed as completed by popcornmix** 2014-06-29 18:47 UTC
