### ISSUE TITLE
Updating to 3.8?

### ISSUE THREAD

**Issue by Ferroin** [raspberrypi/linux#225] opened 2013-02-20 18:50 UTC
Are there any plans to update the tree to Linux 3.8?

There are a number of updates that would be nice to have, especially the stuff in the EXT4 drivers.

While I would be happy to merge the kernel.org mainline into a new branch and submit a pull request, I don't know if there is some special way that people might want it done.

**Comment by popcornmix** [comment] 2013-02-20 19:10
Yes, 3.8 is interesting. For me, mostly due to F2FS.

I'd prefer a new branch (e.g. 3.8.y). I'd prefer it to be rebased on remotes/stable/linux-3.8.y, which I don't think is available yet. 

There's normally a few gotchas of APIs that have changed, or worse APIs that haven't changed but things that need to be done differently. Finding NEED_MACH_MEMORY_H and NEED_MACH_IO_H took me a long time to find last time....

So, if you can get a 3.8 tree up and running, and fix the gotchas, that would be useful.
We can then work out if a PR or some other scheme is best to get it into this repo.

Initially prebuilt firmware with 3.8 will be released to "next" tree until it is deemed stable.

Another question is whether some squashing of commits (particularly dwc_otg and the addition and removal of the 64-bit crypto functions) that produce a lot of conflicts when rebasing is worthwhile.

There's also the question of using mach-bcm2835 as the machine driver, but I accept that's a much harder merge.

(neither of these two point is required for a move to 3.8).

**Comment by Ferroin** [comment] 2013-02-20 19:35
I can definitely get started on it.

Currently, it really isn't all that feasible for me to debug built kernels, but I can almost certainly get 3.8 to build without problems.

**Comment by N8Fear** [comment] 2013-02-20 22:41
I have 3.8.0 building and booting (at least for me, did the same for 3.7 before). I started from a kernel tarball and ported most stuff from this repo over to it. If you want I could surely help.
If you want to take a look my repo is here: git://github.com/N8Fear/rpi-sources.git

**Comment by Ferroin** [comment] 2013-02-20 23:46
Thanks, I'd love some help.

This is the first time I've rebased anything, and I just had to start over because I realized halfway thru (at commit 179 of 323) that I had misunderstood the relation between LOCAL, BASE, and HEAD.

@popcornmix Do you have any problem with just starting a new branch based on git://github.com/N8Fear/rpi-sources.git?  If not, that would be much easier than a rebase.

**Comment by popcornmix** [comment] 2013-02-20 23:53
@Ferroin 
Unfortunately not. The commit history has to be preserved (for many reasons).
One being that commits may be cherry-picked into the upstream kernel.

**Comment by N8Fear** [comment] 2013-02-20 23:57
@popcornmix 
If you can tell me how to start best (clean remotes/stable/linux-3.8.y I presume) and then apply patches on top of that, I can do that. Is there a way to preserve both the commit history of remotes/stable/linux-3.8.y and of this repo?

**Comment by popcornmix** [comment] 2013-02-21 13:16
This is how I did one of the early rebases:
git clone git@github.com:popcornmix/linux.git
git remote add -f stable git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
git rebase --onto v3.2.27 v3.1.9 rpi-patches
(fix conflict)
git rebase --continue
and repeat (you'll get at leats a dozen conflicts)

You'll obviously need to change the tags in the rebase.
However this is quite a tricky procedure. You end up fixing the same lines of code multiple times.
One reason why squashing commits can make life easier.

It may be more useful to take N8Fear's tree, and give it a good test.

**Comment by N8Fear** [comment] 2013-02-21 18:55
I'm about 3/4 through the rebase. Not sure how it will all come together afterwards.
I think somewhen tonight I should have a buildable tree, if I don't hit anything major...

**Comment by N8Fear** [comment] 2013-02-22 23:57
Hi,
it took me a little while longer than expected, but here is my repo with (most likely most of) the commit history: git://github.com/N8Fear/linux.git

To get it build (except for one WLAN driver - still working on that) I had to hack it a bit:
- removal of __devinit and friends due to removal of api
- make zsmalloc bool instead of tristate (otherwise build fails)
- commented out some version specific code
- added typecasts to uncompress.h (to get rid of warnings)

IMPORTANT: CONFIG_RTL8192CU does not build right now - needs fix

Everything should be tested / get a sanity check - with some more time some of the more "hacky" fixes could surly be replaced by something proper...

**Comment by avesal** [comment] 2013-02-23 12:23
Hi N8Fear,
I've downloaded and compiled kernel using your git, but from usb doesn't boot. I see:" Waiting for root device /dev/sda1". If I use as root my SD card, it boots, but with a lot of errors. Can you post me your .config?

Thanks you for your work

**Comment by N8Fear** [comment] 2013-02-23 15:11
I never tried booting from USB, sdcard worked fine for me, though (I just did a quick "testboot" and rebooted to 3.7.9 again afterwards, because there was no grsecpatch for 3.8.0 at that time).
IIRC I used bcmrpi_defconfig without CONFIG_RTL8192CU - my normal config wouldn't help you much (as it is with grsec enabled).
I'm in the process of getting a grsec enabled 3.8.0 right now, but afterwards I can try to replicate you issues.
Maybe you could post some logs so that I can take a look at the errors?

**Comment by avesal** [comment] 2013-02-23 20:08
how can I post logs if system doesn't boot? Should I add any string to cmdline.txt? Sorry, but I'm a very newbie.

Maybe the problem of "waiting for root device.." is that kernel loads pendrive after init?

**Comment by licaon-kter** [comment] 2013-02-23 21:54
@avesal  : did you use a known working _.config_ ? say from your working kernel **zcat /proc/config > ~/.config** copy it and then use **<kerneldir>/make oldconfig**

**Comment by N8Fear** [comment] 2013-02-23 22:20
I was able to boot into 3.8.0. It's running without a serious problem so far. As stated aboce CONFIG_RTL8192CU needs to be disabled to be able to successfully build the kernel and i get an issue with THERMAL_BCM2835 (NULL pointer dereference at boot - seems like the API changed somewhat) - you should disable that one too.
I boot from an sd-card so I don't know, if booting from a pendrive works.
You said it booted (with errors) from sd-card: you could post that errors and you config - maybe that would give some hints about your problem.
Other than that: try what licaon-kter wrote or try bcmrpi_defconfig (and disable the aforementioned two options).

**Comment by N8Fear** [comment] 2013-02-24 01:22
The issue with THERMAL_BCM2835  should be fixed (at least the null pointer dereference). I have to check for correct function, though...

**Comment by avesal** [comment] 2013-02-24 10:56
@licaon-kter 
I used this commands:

root # ARCH=arm make bcmrpi_cutdown_defconfig
root # ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- make oldconfig
root # ARCH=arm CROSS_COMPILE=/usr/bin/armv6j-hardfloat-linux-gnueabi- make -j2

**Comment by licaon-kter** [comment] 2013-02-24 23:49
Use a working config extracted like I pointed out.

**Comment by avesal** [comment] 2013-02-26 11:53
tryed with zcat /proc/config > ~/.config, but nothing: from usb doesn't boot, from sd card boots.

IMHO, I think it's a kernel problem, not a config problem

**Comment by licaon-kter** [comment] 2013-02-26 16:28
what chipset? is the module being build?

**Comment by N8Fear** [comment] 2013-02-26 19:07
can you try to add rootdelay= n to your kernel commandline? (n is the delay in seconds the kernel should wait to mount the rootfs). Start with something higher (maybe 15 or the like) and reduce it, if it works with a delay.

**Comment by popcornmix** [comment] 2013-02-26 20:20
I can confirm that nfs boot hangs:
http://pastebin.com/2yxvaGBB

**Comment by N8Fear** [comment] 2013-02-26 21:23
Fixed build of rtl8192cu

**Comment by N8Fear** [comment] 2013-02-26 21:30
@popcornmix : I can see an error in the paste - most likely I will have to try different bootdevices myself...

**Comment by avesal** [comment] 2013-02-27 09:51
@N8Fear 
Yes, I've tried rootdelay, but doesn't resolv

**Comment by kzemek** [comment] 2013-03-03 11:48
I've backported F2FS to Raspberry's rpi-3.6.y . I completly removed ACL support and had to revert one minor enhancement, both due to being dependent on some newer features, but otherwise everything seems to be working fine (I'm using it as I write).
The changes backported are all of the F2FS commits from current git kernel, so it may be a bit newer than what's in current 3.8 . So of course treat this as triple-experimental: one because it's an experimental filesystem, two because it's backported, and three because it may contain changes not yet in stable.

https://github.com/kzemek/rpi-linux

**Comment by popcornmix** [comment] 2013-03-03 12:10
@kzemek 
Have you measured any improvements or degredations in performance with f2fs on Pi?

**Comment by kzemek** [comment] 2013-03-03 12:38
Only anecdotal, but I find it to be generally more responsive (which would be consistent with f2fs' features). I'm having a hard time to run actual benchmarks, as I have only one SD to experiment with, and that's the one running "main" system.

**Comment by licaon-kter** [comment] 2013-03-03 15:11
Should general **f2fs** benchmarks apply to Pi as well?
'Cause we have:
160GB INTEL SSDSA2M160: http://www.phoronix.com/scan.php?page=article&item=linux_f2fs_benchmarks&num=1
Patriot LX Series 16GB Class 10 SDHC card: http://www.phoronix.com/scan.php?page=article&item=linux_f2fs_sdhc&num=1
160GB INTEL SSDSA2M160: http://www.phoronix.com/scan.php?page=article&item=linux_38_nilfs2&num=1
as data points ;)

**Comment by kzemek** [comment] 2013-03-03 15:42
Sooman Jeong ran some simple benchmarks on an earlier version of F2FS, for a desktop and Galaxy S3:
http://lkml.indiana.edu/hypermail/linux/kernel/1210.2/00005.html

**Comment by licaon-kter** [comment] 2013-03-04 07:23
And from today: http://www.phoronix.com/scan.php?page=article&item=linux_f2fs_usb3&num=1

**Comment by avesal** [comment] 2013-03-07 21:57
@kzemek It's possible backport driver ar5523 to 3.6.11?

**Comment by popcornmix** [comment] 2013-03-08 17:03
@N8Fear any luck investigating the NFS boot hang?

**Comment by N8Fear** [comment] 2013-03-08 18:23
No - I was stricken down by some kind of illness for the whole week. I guess I'll find time for it tomorrow night.

**Comment by kzemek** [comment] 2013-03-11 20:28
@avesal I'll take a look at it once I have time. Rare luxury these days.

**Comment by popcornmix** [comment] 2013-03-28 01:59
I've done my own rebase to 3.8.4. Unfortunately it has the same issue as @N8Fear's with the NFS boot hang.
https://github.com/raspberrypi/linux/tree/rpi-3.8.y-temp

Did anyone get anywhere with debugging this?

**Comment by popcornmix** [comment] 2013-03-29 19:20
dwc_otg.fiq_fix_enable=0
allows the nfs boot to work again. Looks like something has changed in kernel FIQ handling, but this provides a workaround for now.

**Comment by popcornmix** [comment] 2013-04-08 21:44
A prebuilt 3.8.4 is available on next tree. It has f2fs support built in, and fiq_fix_enable defaults to off.
`sudo rpi-update 2c4e92c01ff14d8f3e1ee35b995d430b4e6d1e1b`
should get you it. Not much testing it but appears to work.

**Comment by hvenzke** [comment] 2013-04-10 08:34
I report that prebuilt 3.8.4 works fine on my kingston /sandisk SDHDC/SDHDX 16/32 & 64 G SD cards .

**Comment by licaon-kter** [comment] 2013-04-10 22:57
_Calibrating delay using timer specific routine.._ **2.00 BogoMIPS (lpj=10011)**
on

> Linux raspberrypi 3.8.4+ #406 PREEMPT Mon Apr 8 21:59:50 BST 2013 armv6l GNU/Linux
> BogoMIPS        : 2.00
> CONFIG_NO_HZ=y
> CONFIG_HZ=100
> Apr  2 2013 23:03:25 
> Copyright (c) 2012 Broadcom
> version 381148 (release)

**Comment by hvenzke** [comment] 2013-04-11 08:04
report : 
Patched rpi-3.8.y-temp up with patch-3.8.4-5 & patch-3.8.5-6 without issues..
if nothing went  wrong  at compile ,then my 3.8.6 got ready  by Tommorrow.

**Comment by rbej** [comment] 2013-04-11 12:26
Working fine on OpenElec Rpi. 

Popcornmix. Please update to 3.8.6

**Comment by popcornmix** [comment] 2013-04-11 13:25
@rbej 
Note: that the usb fiq is disabled which will probably cost you about 10% in performance.
Should have a solution for that soon, but for now xbmc may be a bit slower.

**Comment by rbej** [comment] 2013-04-11 14:24
Few fps in menu less than kernel 3.6.11. When i play mkv dts 1080p NFS i dont see any difference. Very stable kernel.

**Comment by popcornmix** [comment] 2013-04-11 16:19
@rbej 
Updated to 3.8.6. Also updated the rtl8192cu wifi driver. It's a rebase so "git pull --rebase" or clean checkout to update source. 
"next" rpi-update firmware will be pushed soon.

**Comment by hvenzke** [comment] 2013-04-11 16:25
nfs & nilfs2  : i see only an few  uninitialized und unused warings  at my 3.8.6 compile .. maybe harmless.
as this been upstream kernel code fix them may not an RPI part..

**Comment by popcornmix** [comment] 2013-04-13 00:16
rpi-3.8.y is updated (another rebase). I think I've fixed the gpio crash. Also more tidying.

**Comment by licaon-kter** [comment] 2013-04-13 09:16
bogoMIPS still bugged

> **pi@raspberrypi:~/ > uname -a ; cat /proc/cpuinfo | grep BogoMIPS ; \
> zcat /proc/config.gz | grep HZ;vcgencmd version**
> Linux raspberrypi 3.8.6+ #410 PREEMPT Thu Apr 11 17:28:47 BST 2013 armv6l GNU/Linux
> BogoMIPS        : 2.00
> CONFIG_NO_HZ=y
> CONFIG_HZ=100
> Apr 11 2013 17:43:15 
> Copyright (c) 2012 Broadcom
> version 383188 (release)

**Comment by rbej** [comment] 2013-04-13 10:55
Only fixed usb fiq (10% less performance) is important. Yesterday i tested new kernel very carefully and i observe few times buffering and stutters when play mkv dts 1080p movies from NFS. Memory usage is little to high, but is acceptable.

**Comment by popcornmix** [comment] 2013-04-13 12:15
@licaon-kter 
I'm afraid bogomips is correct. They are now 2 on raspberry pi. See these threads:
http://comments.gmane.org/gmane.linux.ports.arm.kernel/174598
http://www.spinics.net/lists/sparclinux/msg08550.html

For platforms that use a fixed timer for delays bogomips is now defined to be:
TIMER_FREQ/500000. We have TIMER_FREQ=1000000 and so bogomips = 2.

It's certainly going to cause confusion.

**Comment by licaon-kter** [comment] 2013-04-13 19:19
@popcornmix:  Oh, so I see, I though this might point to some timer issues, but since this the intended behaviour it's OK. 10x for the heads up.

**Comment by hvenzke** [comment] 2013-04-16 00:10
Report :I
- Patched to 3.8.7 , Compiles  without new issues.
- Still the "' makes pointer from integer without a cast and others "  arm warnings etc .. exist as reported for 3.8.4 
- IP_VS Compiled in.
- Hacked popcornmix´s  3.8.4 binary Firmware kernel onto openSuSE 12.3  : Works.

**Comment by popcornmix** [comment] 2013-04-17 16:24
rpi-3.8.y is bumped to 3.8.7 and includes more rebased tidying.
The cast warnings are removed (without casting them away...)

**Comment by hvenzke** [comment] 2013-04-17 16:31
Cool , Great  work.!

**Comment by hvenzke** [comment] 2013-04-17 16:55
you seem bumped to RPI v3.8.8 ..

<pre>
# kversion=$(make -s kernelrelease)
# echo $kversion
3.8.8-4-raspberrypi
</pre>

**Comment by rbej** [comment] 2013-04-18 06:16
Usb fiq is still disabled??

**Comment by popcornmix** [comment] 2013-04-18 10:21
USB fiq still disabled. Waiting for Gordon...

**Comment by ghost** [comment] 2013-04-19 22:00
@popcornmix hi you wrote that with rpi-update 2c4e92c01ff14d8f3e1ee35b995d430b4e6d1e1b one can get a 3.8.4 test-build. is such build also available for a more recent version? and what would the git tag be for that version?
thanks

**Comment by popcornmix** [comment] 2013-04-19 22:29
Just check here:
https://github.com/Hexxeh/rpi-firmware/commits/next
And pick the newest commit hash.

**Comment by ghost** [comment] 2013-04-21 00:53
> Just check here:
> https://github.com/Hexxeh/rpi-firmware/commits/next
> And pick the newest commit hash.

seems to work great!

I migrated 2 RPI's and all is fine.

Folkert van Heusden

## 

MultiTail cok yonlu kullanimli bir program, loglari okumak, verilen
kommandolari yerine getirebilen. Filter, renk verme, merge, 'diff-

## view', vs.  http://www.vanheusden.com/multitail/

Phone: +31-6-41278122, PGP-key: 1F28D8AE, www.vanheusden.com

**Comment by popcornmix** [comment] 2013-04-21 09:46
You can now do:
sudo BRANCH=next rpi-update
to get the latest "next" branch firmware which includes this kernel.

**Comment by hvenzke** [comment] 2013-04-22 07:09
@ popcornmix 
Thanks for work out , but you seems not  added IP_VS and ARPD  to this "next" branch firmware .

As near all RPI distros use your Firmware the issue may still not fixed.
Linux Virtual Server ( ipvsadm +Ldirectord ) Support failed still as require this .
shuold be enabled per defailt.

You added several other IP feagters like gre, hamradio ... as modules.

**Comment by popcornmix** [comment] 2013-04-23 16:04
Another update.
FIQ is now enabled and working for usb.
IP_VS and ARPD modules added

**Comment by hvenzke** [comment] 2013-04-23 16:39
Thanks for your work with IP_VS and ARPD. 
As they work with 3.8.7 well and not harm anything you may can close the seperat tickets.
THANKS !

**Comment by rbej** [comment] 2013-04-26 18:53
Please update to 3.8.9

**Comment by hvenzke** [comment] 2013-04-26 22:41
Please add CONFIG_DLM=m

**Comment by hvenzke** [comment] 2013-04-26 22:43
Note : I tested LXC  Container on 3.8.7 and 3.8.y . result : works exelent .
Please add the LXC Options.

requested  by others as well. : https://github.com/raspberrypi/linux/issues/176

**Comment by hvenzke** [comment] 2013-04-26 22:47
@popcornmix  , 
may you able  to somewhere in future to Create an "SERVER" Image and an "DESKTOP" Image ?
Idea behind  :  kernel Config skope may different .

**Comment by rbej** [comment] 2013-04-27 06:58
I patched 3.8.y to 3.8.10 and everything is ok.

**Comment by popcornmix** [comment] 2013-04-27 11:24
Rebased onto 3.8.10.

**Comment by sanford** [comment] 2013-05-01 08:21
/sys/class/leds appears to be missing

**Comment by ghost** [comment] 2013-05-01 08:23
> /sys/class/leds appears to be missing

I can confirm that.

Folkert van Heusden

## 

MultiTail is een flexibele tool voor het volgen van logfiles en
uitvoer van commando's. Filteren, van kleur voorzien, mergen,

## 'diff-view', etc. http://www.vanheusden.com/multitail/

Phone: +31-6-41278122, PGP-key: 1F28D8AE, www.vanheusden.com

**Comment by ghost** [comment] 2013-05-01 10:51
> Rebased onto 3.8.10.

Please also include the PPS-over-GPIO patch:
http://ntpi.openchaos.org/pps_pi/

pps-gpio patch for the bcm2708 platform and clone the raspberry kernel
tree:
https://raw.github.com/lampeh/rpi-misc/master/linux-pps/linux-rpi-pps-gpio-bcm2708.diff

This enables one to sync the RPI using a GPS with PPS (pulse per second)
signal.

regards

Folkert van Heusden

## 

Multitail es una herramienta flexible que permite visualizar los "log
file" y seguir la ejecución de comandos. Permite filtrar, añadir
colores, combinar archivos, la visualización de diferencias (diff-

## view), etc.  http://www.vanheusden.com/multitail/

Phone: +31-6-41278122, PGP-key: 1F28D8AE, www.vanheusden.com

**Comment by rbej** [comment] 2013-05-01 18:57
Linux 3.9 is now stable. Any chance to 3.9 for Rpi??

**Comment by popcornmix** [comment] 2013-05-01 21:08
We've not finished with 3.8!

3.8.11 has just been pushed. Includes fix for missing /sys/class/leds

**Comment by popcornmix** [comment] 2013-05-01 21:12
And if you really want bleeding edge:
Linux raspberrypi 3.9.0+ #320 PREEMPT Wed May 1 22:02:44 BST 2013 armv6l

https://github.com/raspberrypi/linux/commits/rpi-3.9.y

**Comment by licaon-kter** [comment] 2013-05-02 12:36
What's the status of _3.9.x_ s' **CONFIG_ARCH_BCM2835** ? As I see that, at least for now, the default config still uses **CONFIG_ARCH_BCM2708**.

**Comment by popcornmix** [comment] 2013-05-02 13:00
My guess is that CONFIG_ARCH_BCM2835 will provide a system that boots, but lacks the drivers that have not been upstreamed (e.g. USB, vchiq).

There's a question mark over whether these will ever be upstreamed.

I have no plans to switch to CONFIG_ARCH_BCM2835, but if someone wants to test it, and then add patches for the missing drivers (USB, vchiq) and get a kernel has similar functionality to the existing one, then that would be very beneficial, and should make future kernel updates much easier.

**Comment by licaon-kter** [comment] 2013-05-02 13:42
Are those (USB, vchiq) under some legal (licence) issues or what?

**Comment by popcornmix** [comment] 2013-05-02 14:48
Not license issues. Generally the drivers that are supported on 2835 have been rewritten by a kernel dev (e.g. Stephen Warren) to follow the linux kernel coding standards.

The dwc_otg usb driver is big and ugly, written for an older kernel with ifdefs to handle newer versions. It's unlikely anyone will be willing to rewrite it to get it up to the standards required.

The kernel generally doesn't like interfaces into proprietry firmware, which vchiq may fall foul of, although that's very much a grey area.

A quick search looks like someone may have vchiq merged into a bcm2835 tree:
https://github.com/hackerspace/rpi-linux/commit/f7c0d48cd2e4b98623ebed50c3ff409b02837e16

**Comment by ghost** [comment] 2013-05-02 15:04
@popcornmix

> Rebased onto 3.8.10.

Please also include the PPS-over-GPIO patch:
http://ntpi.openchaos.org/pps_pi/

pps-gpio patch for the bcm2708 platform and clone the raspberry kernel
tree:
https://raw.github.com/lampeh/rpi-misc/master/linux-pps/linux-rpi-pps-gpio-bcm2708.diff

This enables one to sync the RPI using a GPS with PPS (pulse per second)
signal.

regards

Folkert van Heusden

## 

Multitail es una herramienta flexible que permite visualizar los "log
file" y seguir la ejecución de comandos. Permite filtrar, añadir
colores, combinar archivos, la visualización de diferencias (diff-

## view), etc.  http://www.vanheusden.com/multitail/

Phone: +31-6-41278122, PGP-key: 1F28D8AE, www.vanheusden.com

**Comment by popcornmix** [comment] 2013-05-02 15:33
@flok99 
Please open a new issue.

**Comment by hvenzke** [comment] 2013-05-02 15:45
@popcornmix  @flok99 pps-gpio #109  .. just update it there and close the old shit :-)

**Comment by rbej** [comment] 2013-05-08 07:57
Please updated to 3.8.12

**Comment by hvenzke** [comment] 2013-05-08 08:18
CONFIG_USB_HCD_BCMA=m faild  see #291 , shuold be fixed with  update to 3.8.12 please.

**Comment by popcornmix** [comment] 2013-05-08 11:11
Rebased to 3.8.12. Also updated 3.9.y kernel to 3.9.1.

**Comment by hvenzke** [comment] 2013-05-08 14:09
@popcornmix  please add the DLM & DRBD Options to the default RPI Firmware  ( CONFIG_DLM=m  )
 to to get corosync  & pacemaker  to work with DRBD

**Comment by popcornmix** [comment] 2013-05-08 22:26
I spotted a possible spinlock issue in sdcard driver, and have committed a fix.
I've pushed it to next firmware tree.

**Comment by matiasdelellis** [comment] 2013-05-09 19:22
Sorry,
How I can test the 3.8 branch?

**Comment by hvenzke** [comment] 2013-05-09 20:36
@matiasdelellis ,

folow that guide : http://www.raspberrypi.org/phpBB3/viewtopic.php?f=87&t=40664

**Comment by Ferroin** [comment] 2013-05-10 01:08
Is there any major reason at this point to not transition to using the 3.8 firmware tree as the master branch?

**Comment by popcornmix** [comment] 2013-05-10 10:36
This is the main obstacle:
https://github.com/raspberrypi/linux/issues/280

**Comment by rbej** [comment] 2013-05-11 21:34
Please updated to 3.8.13 and 3.9.2

**Comment by popcornmix** [comment] 2013-05-12 11:31
@rbej 
Kernels updated.

**Comment by rbej** [comment] 2013-05-19 19:40
3.9.3 is out ;)

**Comment by licaon-kter** [comment] 2013-05-20 08:34
Any reason to keep up the update race every day?

**Comment by rbej** [comment] 2013-06-08 06:29
3.9.5 is out. Please updated :). Thanks.

**Comment by popcornmix** [comment] 2013-06-08 21:25
3.9.5 is pushed.

**Comment by popcornmix** [comment] 2013-06-09 14:17
I've updated the "next" tree to 3.9.5.
It's been confirmed that 3.8 won't have long term support, and it hasn't been updated (upstream) for some time, so I don't see a reason to stay with 3.8.
There's no guarantee that 3.9 will have long support either, but it is at least getting regular updates.

**Comment by hvenzke** [comment] 2013-12-22 17:11
My Pi´s left kicked off 3.8.y .. so close if you wisch

**Closed as completed** 2013-12-23 23:49 UTC
