### ISSUE TITLE
please update the 4.9 branch

### ISSUE THREAD

**Issue by stefson** [raspberrypi/linux#2495] opened 2018-04-07 23:40 UTC
hey there, 

it would be great to have the patches from kernel.org integrated into the 4.9 branch, it is still at 4.9.80 at the moment. All patches apply but for this one, which already got merged into the rpi 4.9 branch: 

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/diff/drivers/usb/gadget/function/f_hid.c?id=v4.9.92&id2=v4.9.89

the conflict can be solved easily, it shouldn't require any troublesome backporting at all.

**Comment by popcornmix** [comment] 2018-04-09 13:46
The problem is we are no longer testing the 4.9 kernel as it is no longer used by raspbian.
We'd recommend users switch to the 4.14 kernel. Any reason not to do this?

**Comment by smp79** [comment] 2018-04-10 14:58
I'm also have to use kernel 4.9 for my LibreELEC builds. With kernel 4.14 there are audio dropouts during heavy sdcard i/o activity. It is impossible to watch and record the TV channel at the same time. No such issue then building with kernel 4.9.

**Comment by stefson** [comment] 2018-04-11 16:56
There are more OS out there but raspian, Gentoo for that matter or flavours of Ubuntu. I don't really trust 4.14 yet, it had terrible bugs for weeks. I can always maintain my own kernel tree, but it would be great to see the patches from kernel.org added.

**Comment by JamesH65** [comment] 2018-04-11 17:20
We've been testing 4.14 for months, so from my point of view its seems pretty stable. Are there any particular issues you are seeing with 4.14 that need fixing? 

With regard to other OS's, they are indeed other OS's and really should be supported by the people who supply them. It would be a drag on our dev schedule to have to support other people's OS's as well as our own, back porting is often non-trivial.

**Comment by JamesH65** [comment] 2018-04-20 13:46
Closing as a Won't Fix. This means that although the issue is acknowledged, it is felt that no further action is likely. This may be down to a bad benefit vs cost analysis, or it may actually not be possible to fix.

**Closed as completed by JamesH65** 2018-04-20 13:46 UTC
