### ISSUE TITLE
add USB HID Touchscreen support for Teensy 3.2?

### ISSUE THREAD

**Issue by epikao** [raspberrypi/linux#2336] opened 2018-01-06 07:20 UTC
Hello,
with teensy 3.2 we can simulate a USB touchscreen, with
TouchscreenUSB.press(finger, x, y);
TouchscreenUSB.release(finger);

see also (touch descriptor etc.)
https://forum.pjrc.com/threads/32331-USB-HID-Touchscreen-support-needed

Unfortunately raspian can only shows touch if press touch but as soon as a release the touch freezes...
On Windows or Mac it works fine but not with Raspbian, can you add support?

see also:
https://github.com/raspberrypi/linux/issues/718#issuecomment-355728914

**Comment by epikao** [comment] 2018-01-06 18:17
No Help? I am a dummy regarding build linux kernel etc. So it would be really appreciate if somebody could add USB touchscreen support on Raspbian for the teensy USB touch simulator?

**Comment by epikao** [comment] 2018-01-06 22:38
it's a little bit urgent for me. Maybe popcornmix can help? Does somebody know how, where I can contact him? thankyou

**Comment by JamesH65** [comment] 2018-01-07 11:32
It's the weekend. Everyone is at home doing stuff that isn't work. I'm sure if someone is available, they can start to help out from Monday.

I think you might also need to be a bit more spercific about what you actually want., because from your post isn't clear to me. Is it a particular kernel option?

**Comment by epikao** [comment] 2018-01-07 15:37
don't know if is a kernel option or not. The only one I know is that teensy USB Touchscreen (Simulator) is working perfectly on Windows or Mac but not on Linux? respectively not on my Raspberry with Raspbian Jessie Distro/OS (from 2017.04)...
I guess that Standard USB HID Touchscreen driver is already included on Raspbian?
However, a press Touch I can see properly, but as soon I remove my finger from touch the touch is freeze and it does not working any more.

**Comment by pelwell** [comment] 2018-01-07 16:16
You're still running Jessie? Things have moved on since April last year, so your first step is to update to the latest Stretch and see if that makes a difference.

**Comment by epikao** [comment] 2018-01-07 19:01
yes jessie, I also tried newest ubuntu mate but with exactly the same problem... so I do not believe that it will work with newest raspbian/jessie, anyway I will try it this evening.

**Comment by JamesH65** [comment] 2018-01-07 19:23
You should use the latest Raspbian (Stretch) - that is the RPF supported distribution and has all the latest patches. I have no idea what kernel Ubuntu Mate is running, it's not ours.

**Comment by epikao** [comment] 2018-01-07 21:30
the issue with rpi stretch (desktop) 2017.11.29 unfortunately is the same :-(, also did apt-get update. 
First touch works (mouse symbol is moving) but after release respectively remove the finger the touch is freeze, no further reaction with touch. 
What can I do?

**Comment by epikao** [comment] 2018-01-07 22:17
something about touch ID:
#elif defined(USB_HID_TOUCHSCREEN)
  #define VENDOR_ID		0x16C0
  #define PRODUCT_ID		0x04D4
  #define MANUFACTURER_NAME	{'T','e','e','n','s','y','d','u','i','n','o'}
  #define MANUFACTURER_NAME_LEN	11
  #define PRODUCT_NAME		{'K','e','y','b','o','a','r','d','/','M','o','u','s','e','/','T','o','u','c','h','s','c','r','e','e','n'}
  #define PRODUCT_NAME_LEN	26
  #define EP0_SIZE		64
  #define NUM_ENDPOINTS         6
  #define NUM_USB_BUFFERS	20
  #define NUM_INTERFACE		5
  #define SEREMU_INTERFACE      2	// Serial emulation
  #define SEREMU_TX_ENDPOINT    1
  #define SEREMU_TX_SIZE        64
  #define SEREMU_TX_INTERVAL    1
  #define SEREMU_RX_ENDPOINT    2
  #define SEREMU_RX_SIZE        32
  #define SEREMU_RX_INTERVAL    2
  #define KEYBOARD_INTERFACE    0	// Keyboard
  #define KEYBOARD_ENDPOINT     3
  #define KEYBOARD_SIZE         8
  #define KEYBOARD_INTERVAL     1
  #define KEYMEDIA_INTERFACE    3	// Keyboard Media Keys
  #define KEYMEDIA_ENDPOINT     4
  #define KEYMEDIA_SIZE         8
  #define KEYMEDIA_INTERVAL     4
  #define MOUSE_INTERFACE       1	// Mouse
  #define MOUSE_ENDPOINT        6
  #define MOUSE_SIZE            8
  #define MOUSE_INTERVAL        2
  #define MULTITOUCH_INTERFACE  4	// Touchscreen
  #define MULTITOUCH_ENDPOINT   5
  #define MULTITOUCH_SIZE       9
  #define MULTITOUCH_FINGERS    10
  #define ENDPOINT1_CONFIG	ENDPOINT_TRANSIMIT_ONLY
  #define ENDPOINT2_CONFIG	ENDPOINT_RECEIVE_ONLY
  #define ENDPOINT3_CONFIG	ENDPOINT_TRANSIMIT_ONLY
  #define ENDPOINT4_CONFIG	ENDPOINT_TRANSIMIT_ONLY
  #define ENDPOINT5_CONFIG	ENDPOINT_TRANSIMIT_ONLY
  #define ENDPOINT6_CONFIG	ENDPOINT_TRANSIMIT_ONLY
...etc.

And Report:
static uint8_t multitouch_report_desc[] = {
        0x05, 0x0D,                     // Usage Page (Digitizer)
        0x09, 0x04,                     // Usage (Touch Screen)
        0xa1, 0x01,                     // Collection (Application)
        0x09, 0x22,                     //   Usage (Finger)
        0xA1, 0x02,                     //   Collection (Logical)
        0x09, 0x42,                     //     Usage (Tip Switch)
        0x15, 0x00,                     //     Logical Minimum (0)
        0x25, 0x01,                     //     Logical Maximum (1)
        0x75, 0x01,                     //     Report Size (1)
        0x95, 0x01,                     //     Report Count (1)
        0x81, 0x02,                     //     Input (variable,absolute)
        0x09, 0x30,                     //     Usage (Pressure)
        0x25, 0x7F,                     //     Logical Maximum (127)
        0x75, 0x07,                     //     Report Size (7)
        0x95, 0x01,                     //     Report Count (1)
        0x81, 0x02,                     //     Input (variable,absolute)
        0x09, 0x51,                     //     Usage (Contact Identifier)
        0x26, 0xFF, 0x00,               //     Logical Maximum (255)
        0x75, 0x08,                     //     Report Size (8)
        0x95, 0x01,                     //     Report Count (1)
        0x81, 0x02,                     //     Input (variable,absolute)
        0x05, 0x01,                     //     Usage Page (Generic Desktop)
        0x09, 0x30,                     //     Usage (X)
        0x09, 0x31,                     //     Usage (Y)
        0x26, 0xFF, 0x7F,               //     Logical Maximum (32767)
        0x65, 0x00,                     //     Unit (None)  <-- probably needs real units?
        0x75, 0x10,                     //     Report Size (16)
        0x95, 0x02,                     //     Report Count (2)
        0x81, 0x02,                     //     Input (variable,absolute)
        0xC0,                           //   End Collection
        0x05, 0x0D,                     //   Usage Page (Digitizer)
        0x27, 0xFF, 0xFF, 0, 0,         //   Logical Maximum (65535)
        0x75, 0x10,                     //   Report Size (16)
        0x95, 0x01,                     //   Report Count (1)
        0x09, 0x56,                     //   Usage (Scan Time)
        0x81, 0x02,                     //   Input (variable,absolute)
        0x09, 0x54,                     //   Usage (Contact Count)
        0x25, MULTITOUCH_FINGERS,       //   Logical Maximum (10)
        0x75, 0x08,                     //   Report Size (8)
        0x95, 0x01,                     //   Report Count (1)
        0x81, 0x02,                     //   Input (variable,absolute)
        0x05, 0x0D,                     //   Usage Page (Digitizers)
        0x09, 0x55,                     //   Usage (Contact Count Maximum)
        0x25, MULTITOUCH_FINGERS,       //   Logical Maximum (10)
        0x75, 0x08,                     //   Report Size (8)
        0x95, 0x01,                     //   Report Count (1)
        0xB1, 0x02,                     //   Feature (variable,absolute)
        0xC0                            // End Collection
};
#endif

**Comment by pelwell** [comment] 2018-01-08 10:11
We don't have the resources to investigate Teensy and what it needs in order to work on Raspbian. I suggest you ask the Teensy community if one of them can explain exactly what is needed, or at least what the problem is.

One thing you could try yourself is running `xev` under Raspbian and Ubuntu Mate to see which X events are generated in response to touch screen activity. `xev > touch_log.txt` will capture the events to a file - try working through the same activities on both platforms in a systematic way, then comparing the log files. If nothing else it may show whether X events are stopping on Raspbian or whether they are still being generated and the GUI is locking up.

**Comment by epikao** [comment] 2018-01-08 10:47
>We don't have the resources to investigate Teensy and what it needs in order to work on Raspbian. I >suggest you ask the Teensy community if one of them can explain exactly what is needed, or at least what >the problem is.

they think the problem is X11 from Linux which is full of bug :-((

**Comment by epikao** [comment] 2018-01-08 12:28
Hello, I have two USB touchscreens, the one with Atmel mXT1188s Controller and the other is as mention the Teensy 3.2 Controller.
Under xev with the Atmel Touchscreen I see ButtonPress event and ButtonRelease events.
With Teensy Touchscreen I only see ButtonPress but no ButtonRelease events... so why the Release Events are not recognise properly? As it looks that nobody has time - I am also willing to pay for that solution? The USB HID Touchscreen Descriptor Code etc. from Teensy is open source....

(PS: Atmel Touchscreen is working properly with Raspbian)

**Comment by pelwell** [comment] 2018-01-08 12:35
Try the Advanced Users or Interfacing forums at https://raspberrypi.org/forums, or whatever the Teensy equivalent might be - your financial incentive is more likely to be productive there.

**Comment by epikao** [comment] 2018-01-08 12:58
ok :-( but why the guy from follow topic with same problem you solved but my (same problem) not?
 => https://github.com/raspberrypi/linux/issues/718#issuecomment-355728914

**Comment by JamesH65** [comment] 2018-01-08 13:03
Because that was a simple kernel config change, whereas your issue appears to be a bug in the teesy toushscreen driver.  And we don't know anything about those, or even have equipment to test with, and, TBH, we prefer to fix bugs in our own stuff before we start fixing bugs other peoples stuff.

**Comment by pelwell** [comment] 2018-01-08 13:04
If you identify the changes which need to be made - as happened in the other thread - then there is a good chance that they would be accepted, but I suspect this issue is more complicated, and you need to accept that and enlist the help of a Teensy dev (or advanced user).

**Comment by epikao** [comment] 2018-01-08 15:08
_> whereas your issue appears to be a bug in the teesy toushscreen driver._

I think is more a Linux / X11 problem and not a teensy, as my teensy is working properly with Windows and Mac....

**Comment by epikao** [comment] 2018-01-11 14:58
Please note: It's definetly a Linux problem, because I have now tested with windows 10 IOT on Raspberry and Touchscreen Teensy is working properly!
But it does **not** work on Raspbian, Jessie, not on OSMC and also not on Linux Ubuntu Mate!!

**Comment by jakemagee** [comment] 2018-01-11 17:39
Have you tried testing with an x86 Linux system?  You may very well be having an issue with Linux / X11, but this wouldn't be the correct place to seek help unless you can provide details that indicate it is specifically related to the Raspberry Pi.

**Comment by epikao** [comment] 2018-01-11 18:47
and which Linux for x86 should I try? Ubuntu?

**Comment by jakemagee** [comment] 2018-01-11 19:14
I think that would be an adequate place to start.  And if it still doesn't work, you'll need to then find a more generic linux / X11 forum to post on.  Once you get it working on an x86 machine, it will be much easier to determine the fix for a Raspberry Pi.

**Comment by epikao** [comment] 2018-01-11 19:19
yes but which linux distro do you recommend for testing that on a x86 sytem? ubuntu, suse etc??

**Comment by pelwell** [comment] 2018-01-11 19:52
See previous answer. @jakemagee said that Ubuntu would be a reasonable place to start.

**Comment by jakemagee** [comment] 2018-01-11 19:52
Yes, that's what I was saying.  Try it on a x86 system with Ubuntu 17.04.

**Comment by epikao** [comment] 2018-01-11 22:05
ok. I will try tomorrow to install Ubuntu 17.04 on my old laptop.
at the moment I can only hope that in the near future X11 will be replaced with Wayland or Mir....

**Comment by epikao** [comment] 2018-01-13 20:12
with Ubuntu 17.04 on my old laptop I have the same problem... so I think teensy Code is not compatible to Linux. Teensy developer are now checking the problem... Hope they will find a solution...

**Comment by jakemagee** [comment] 2018-01-13 23:54
Sounds good.  Can you close the issue for now?  If you get it working on a x86 Linux machine and it still doesn't work on a Raspberry Pi, you could open back up an issue.

**Closed as completed** 2018-01-16 12:44 UTC
