### ISSUE TITLE
cc2520 SPI Driver support

### ISSUE THREAD

**Issue by brycejacobs** [raspberrypi/linux#684] opened 2014-09-09 21:31 UTC
Please reference commit 
https://github.com/torvalds/linux/commit/0da6bc8cc3417a5e452efb886ff2c61e72b743d6 

What are the chances of having this merged over into this repo?

Thanks, 
Bryce Jacobs

**Comment by GuacoIV** [comment] 2014-09-10 04:30
I support that idea!

**Comment by popcornmix** [comment] 2014-09-10 12:01
Have you tried adding the commit to 3.12 tree, building and confirming it works?
I think we need some evidence that it works, and some evidence of significant demand for it before adding.

**Comment by brycejacobs** [comment] 2014-11-21 07:58
@popcornmix So it seems the cc2520 driver landed in the 3.17.y branch.

I have compiled the kernel with DT support according to the wiki: https://github.com/raspberrypi/linux/wiki/Device-Tree-on-ARCH_BCM2708
and seem to get a hangup on load when it gets to smsc95xx ....

If I disable DT support and load a fresh 3.17.y kernel it will work fine, however the cc2520 requires Device Tree support. I am going to try compiling the kernel with the BCM2835 config instead of the default config and see what happens. 

Will attempt to get the dmesg log on the next go around.

**Comment by popcornmix** [comment] 2014-11-21 12:55
I'm hoping we will push out a BRANCH=next firmware using 3.17 kernel with DT enabled in the next couple of weeks. This is mostly for HAT support, but may make using the cc2520 driver more straightforward.

**Comment by brycejacobs** [comment] 2014-11-21 13:16
Maybe there is some confusion on my behalf as far as getting the DT support working. I have the master branch firmware in the raspberrypi/firmware repo, does the firmware compilation version have to match up with my kernel version of 3.17? 

From the wiki link I posted above I was under the assumption that you compile the kernel, add the .dtb & zImage files to boot, then swap the config.txt kernel along with adding the new parameters. (As well as the adding of /lib/{firmware, modules}). Is there something I'm missing here? I have all proper .config variables in place for the DT support, as well as the IEEE802154, CC2520, etc. 

Has anyone had a successful run at making Device Tree support work for 3.17? I was looking on another issue thread at a gentleman who was having a hard time with DT being enabled for 3.16 but came to the understanding that there was a problem in his config.txt file. Is there a chance someone else can check to see if DT support on 3.17 w/ BCM2708 works?

I am on a deadline so any help whatsoever would be much appreciated. @popcornmix

**Comment by matthiasklein** [comment] 2014-11-21 13:30
I run the following trees with u-boot successful with Device Tree support:
- https://github.com/pietrushnic/rpi-dt-linux
- mainline Linux
- linux-next

For USB on the B+ you need the following patch: https://git.kernel.org/cgit/linux/kernel/git/arm/arm-soc.git/commit/?h=next/dt&id=ba2a1d6959acfc387c20eae6480b1c4b3bbc5950

**Comment by brycejacobs** [comment] 2014-11-21 14:14
@matthiasklein Out of curiousity, are you on the 3.17 branch? Also, are you running on BCM2835 or BCM2708?

**Comment by matthiasklein** [comment] 2014-11-21 14:20
Yes, on pietrushnic's tree I am on the rpi-3.17-y branch. What do you mean with  BCM2835 vs BCM2708? Upstream linux uses CONFIG_ARCH_BCM2835=y

**Comment by brycejacobs** [comment] 2014-11-21 16:02
The reason I was asking was that the wiki I posted was BCM2708 which seemed like an easier way to go at first. I didn't know if pietrushnic and crew were supporting the BCM2708, didn't see your last part of the post about USB support which is what my initial concern was.

**Comment by notro** [comment] 2014-11-21 17:44
**ARCH_BCM2708 vs. ARCH_BCM2835**
ARCH_BCM2708 is the architecture config option used in the Broadcom patches that is used in raspberrypi/linux.
ARCH_BCM2835 is the architecture used in the upstream kernel which is DT enabled.
- [Why is the CPU sometimes referred to as BCM2708, sometimes BCM2835?](http://raspberrypi.stackexchange.com/questions/840/why-is-the-cpu-sometimes-referred-to-as-bcm2708-sometimes-bcm2835)
- [BCM2708vsBCM2835](https://github.com/notro/rpi-firmware/wiki/BCM2708vsBCM2835)

I submitted some patches giving DT support with ARCH_BCM2708. The problem is that it won't build on 3.17 due to changes in the pinctrl subsystem. I haven't bothered with it, since I haven't heard about anyone using this except myself.
Currently I'm using pietrushnic's tree for my DT based work, but it's is lacking in driver support. I use it for driver development, so that doesn't bother me.

> I'm hoping we will push out a BRANCH=next firmware using 3.17 kernel with DT enabled in the next couple of weeks.

@popcornmix ARCH_BCM2708 or ARCH_BCM2835?

**Comment by popcornmix** [comment] 2014-11-21 18:40
@notro this will be ARCH_BCM2708.  
ARCH_BCM2835 is the goal, but longer term.

**Comment by brycejacobs** [comment] 2014-11-21 21:01
@notro In order to get the build compiling, the disable option has to be removed from the pinctrl-bcm2708.c similar to what was done in this commit over in pietrushnic's upstream:

https://github.com/pietrushnic/rpi-dt-linux/commit/2243a87d90b42eb38bc281957df3e57c712b5e56#diff-957df055023a4647f420276b516adaec

I get the kernel booting, it just hangups when the smsc95xx gets loaded. This is only with DT support enabled, disabling and compiling the kernel will boot. I can't seem to get any useful output in kernel logs to use, haven't any experience with debugging a kernel. I turned on DYNAMIC_DEBUG but haven't had any luck.

**Comment by brycejacobs** [comment] 2014-11-21 21:02
I am getting my environment set up at the LSU Hermione cluster so I can have a faster turn around time in compiling the kernel, hopefully can lead to faster turnaround time.

**Comment by notro** [comment] 2014-11-21 21:04
I'm working on a patch...

**Comment by brycejacobs** [comment] 2014-11-21 21:05
@notro That's great, is there anything that you need help with? I am not extremely experienced when it comes to kernel experience but can go get some legwork done if needed.

**Comment by notro** [comment] 2014-11-21 21:07
Thanks, but the work is trivial. It just takes some time to turn it into a Pull Request.

**Comment by notro** [comment] 2014-11-22 00:37
A bit more work than I thought, so I started a new thread #728

**Comment by Ruffio** [comment] 2016-08-10 14:21
@popasquat89 has this issue been resolved? If yes, then please close this issue.

**Comment by P33M** [comment] 2017-05-04 15:17
Latest shipped kernel is 4.9, the driver has been enabled for ages.

**Closed as completed by P33M** 2017-05-04 15:17 UTC
