### ISSUE TITLE
kernel oops

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#379] opened 2013-09-20 12:22 UTC
We get kernel OOPs on two Raspberry Pis on a regular base. As they occure on two different Raspberry Pis we are pretty sure it's not a hardware problem

![raspbian_kernel_bug](https://f.cloud.github.com/assets/4060015/1180258/549d606c-21ef-11e3-8606-d8ca33f0ace5.jpg)

**Comment by popcornmix** [comment] 2013-09-20 12:34
I can't view the link: "cannot be displayed, because it contains errors"

**Comment by ghost** [comment] 2013-09-20 13:11
![raspbian_kernel_bug](https://f.cloud.github.com/assets/4060015/1180522/1f46d70c-21f6-11e3-9b77-99e28c6efec2.jpg)

Attached it again.

**Comment by popcornmix** [comment] 2013-09-20 13:14
I can't view the link: "cannot be displayed, because it contains errors"

**Comment by licaon-kter** [comment] 2013-09-20 14:25
I can see them just fine

**Comment by popcornmix** [comment] 2013-09-20 16:50
Yes, images are working now,
@r8qt7 
Pressing enter may allow more debug info to be displayed showing the call stack (if keyboard is still working)
Looks like the failure is in rtl8192cu wifi driver.

**Comment by richard-tx** [comment] 2014-01-10 04:05
I have seen this panic as well but it may be related to another very reproducible panic i have reported regarding the usb driver.

**Comment by Ruffio** [comment] 2016-08-10 10:52
@r8qt7 has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment] 2016-08-29 15:49
@popcornmix consider to close this, as it is an old issue with no activity, and there haven't been any response to my ping 19 days ago

**Closed as completed** 2016-08-29 18:00 UTC
