### ISSUE TITLE
Pi Camera module v2 not working in Chromium/Electron with kernel v4.4

### ISSUE THREAD

**Issue by mgcrea** [raspberrypi/linux#1499] opened 2016-05-28 10:07 UTC
I'm struggling to make the Pi Camera module v2 work inside Chromium/Electron (while raspistill and python PiCamera do work) on an up-to-date Ubuntu Mate 16.04. 

When I start [electron](http://electron.atom.io/) on this url: https://simpl.info/getusermedia/sources
I get a black square with the following logs inside `/var/log/kern.log`:

```
May 28 11:42:08 player-a8c4 kernel: [  269.703642] bcm2835_v4l2: error 0 waiting for sync completion
May 28 11:42:09 player-a8c4 kernel: [  270.708122] bcm2835-v4l2: error 0 waiting for frame completion
May 28 11:42:12 player-a8c4 kernel: [  273.702832] bcm2835_v4l2: error 0 waiting for sync completion
May 28 11:42:15 player-a8c4 kernel: [  276.705910] bcm2835_v4l2: error 0 waiting for sync completion
May 28 11:42:15 player-a8c4 kernel: [  276.705940] bcm2835-v4l2: Failed disabling camera, ret -62
May 28 11:42:15 player-a8c4 kernel: [  276.705951] bcm2835-v4l2: Failed to disable camera
May 28 11:42:15 player-a8c4 kernel: [  276.705961] ------------[ cut here ]------------
May 28 11:42:15 player-a8c4 kernel: [  276.705996] WARNING: CPU: 3 PID: 5702 at drivers/media/v4l2-core/videobuf2-core.c:1670 __vb2_queue_cancel+0xfc/0x160 [videobuf2_core]()
May 28 11:42:15 player-a8c4 kernel: [  276.706006] Modules linked in: tun rfcomm fuse xt_multiport xt_conntrack ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables x_tables nf_nat nf_conntrack br_netfilter bridge stp llc overlay bnep hci_uart btbcm bluetooth evdev joydev brcmfmac brcmutil cfg80211 rfkill bcm2835_gpiomem bcm2835_wdt rpi_ft5406 uio_pdrv_genirq rpi_backlight uio snd_bcm2835 snd_pcm_oss snd_mixer_oss snd_seq_dummy snd_pcm snd_seq_oss snd_seq_midi snd_rawmidi snd_seq_midi_event snd_seq snd_seq_device snd_timer snd bcm2835_v4l2 videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core v4l2_common videodev media ipv6
May 28 11:42:15 player-a8c4 kernel: [  276.706254] CPU: 3 PID: 5702 Comm: V4L2CaptureThre Not tainted 4.4.11-v7+ #888
May 28 11:42:15 player-a8c4 kernel: [  276.706262] Hardware name: BCM2709
May 28 11:42:15 player-a8c4 kernel: [  276.706303] [<80018724>] (unwind_backtrace) from [<80014058>] (show_stack+0x20/0x24)
May 28 11:42:15 player-a8c4 kernel: [  276.706329] [<80014058>] (show_stack) from [<803205a4>] (dump_stack+0xd4/0x118)
May 28 11:42:15 player-a8c4 kernel: [  276.706354] [<803205a4>] (dump_stack) from [<80025300>] (warn_slowpath_common+0x98/0xc8)
May 28 11:42:15 player-a8c4 kernel: [  276.706379] [<80025300>] (warn_slowpath_common) from [<800253ec>] (warn_slowpath_null+0x2c/0x34)
May 28 11:42:15 player-a8c4 kernel: [  276.706405] [<800253ec>] (warn_slowpath_null) from [<7f0b328c>] (__vb2_queue_cancel+0xfc/0x160 [videobuf2_core])
May 28 11:42:15 player-a8c4 kernel: [  276.706439] [<7f0b328c>] (__vb2_queue_cancel [videobuf2_core]) from [<7f0b3878>] (vb2_core_streamoff+0x44/0xac [videobuf2_core])
May 28 11:42:15 player-a8c4 kernel: [  276.706473] [<7f0b3878>] (vb2_core_streamoff [videobuf2_core]) from [<7f0bd5dc>] (vb2_streamoff+0x40/0x60 [videobuf2_v4l2])
May 28 11:42:15 player-a8c4 kernel: [  276.706504] [<7f0bd5dc>] (vb2_streamoff [videobuf2_v4l2]) from [<7f0bd64c>] (vb2_ioctl_streamoff+0x50/0x54 [videobuf2_v4l2])
May 28 11:42:15 player-a8c4 kernel: [  276.706553] [<7f0bd64c>] (vb2_ioctl_streamoff [videobuf2_v4l2]) from [<7f079d40>] (v4l_streamoff+0x28/0x2c [videodev])
May 28 11:42:15 player-a8c4 kernel: [  276.706609] [<7f079d40>] (v4l_streamoff [videodev]) from [<7f07de68>] (__video_do_ioctl+0x2a0/0x314 [videodev])
May 28 11:42:15 player-a8c4 kernel: [  276.706664] [<7f07de68>] (__video_do_ioctl [videodev]) from [<7f07d720>] (video_usercopy+0x188/0x60c [videodev])
May 28 11:42:15 player-a8c4 kernel: [  276.706724] [<7f07d720>] (video_usercopy [videodev]) from [<7f07dbc4>] (video_ioctl2+0x20/0x24 [videodev])
May 28 11:42:15 player-a8c4 kernel: [  276.706780] [<7f07dbc4>] (video_ioctl2 [videodev]) from [<7f078720>] (v4l2_ioctl+0xd4/0xe8 [videodev])
May 28 11:42:15 player-a8c4 kernel: [  276.706821] [<7f078720>] (v4l2_ioctl [videodev]) from [<80169288>] (do_vfs_ioctl+0x424/0x614)
May 28 11:42:15 player-a8c4 kernel: [  276.706843] [<80169288>] (do_vfs_ioctl) from [<801694bc>] (SyS_ioctl+0x44/0x6c)
May 28 11:42:15 player-a8c4 kernel: [  276.706865] [<801694bc>] (SyS_ioctl) from [<8000fb40>] (ret_fast_syscall+0x0/0x1c)
May 28 11:42:15 player-a8c4 kernel: [  276.706887] ---[ end trace 92cd1901b66857da ]---
```

``` bash
# uname -a
Linux player-a8c4 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l armv7l armv7l GNU/Linux
```

After that, the camera module seems stuck and any further `raspistill` won't work.

Any ideas?

---

Might be related to #817?

**Comment by 6by9** [comment] 2016-05-28 10:36
Duplicate of #1498 - ignoring.

**Closed as completed** 2016-05-28 11:06 UTC
