### ISSUE TITLE
Jessie: apt-get freezes while/after unpacking vim-runtime

### ISSUE THREAD

**Issue by lhartvik** [raspberrypi/linux#1162] opened 2015-10-12 11:32 UTC
Model: Raspberry Pi 2 B+
Image: Jessie (September 2015)
1. Created a new raspbian on a 16 Gb memory card.
2. Booted the raspberry pi 2, quit raspi-config(no overclocking).
3. sudo apt-get update
4. sudo apt-get install vim
The raspberry pi freezes on "Unpacking vim-runtime". 

I did this twice yesterday. Then tried the same on Wheezy(May 2015), and no issues. 
apt-get also works a lot faster on Wheezy.

**Comment by XECDesign** [comment] 2015-10-12 12:05
Tried it and it worked fine. Takes a suspiciously long amount of time, but it doesn't hang. If this can be considered a bug, it should probably go to debian or dpkg maintainers, since it's not a linux kernel issue.

**Comment by PeterPablo** [comment] 2015-10-12 14:04
Even though it might be another issue, I'd like to note that I had to **disable IPv6** on my freshly installed Raspbian Jessie, as `apt-get` would either not resolve the repositories at all or it would take a very long time. Possibly this is an issue with my local network not being (fully) capable of IPv6, but I certainly did not face this problem in Raspbian Wheezy.

**Comment by SharkWipf** [comment] 2016-01-26 18:41
Facing this issue with vim as well, while installing vim-runtime the Raspberry Pi becomes completely unresponsive, both over ssh and locally. It also stops replying to any pings. 
I don't think this can be considered an upstream issue, a package installation shouldn't be able to cause the entire Raspberry Pi to lock up, regardless what kind of package it is. 
I've also noticed the same behavior on other packages during an apt-get upgrade on a clean system.

Software: 
- Everything downloaded and installed today, latest Raspbian from the RasPi site.
- Filesystem expanded
- No overclocks whatsoever
- Vanilla config.txt
- Used several power supplies including ones sold specifically for the RasPi.
- Default amount of swap Raspbian creates, nothing running except ssh (and apt). No GUI.

Hardware: 
- Brand new RasPi 2 B, arrived today
- Kingston Class 10 MicroSD card
- All unnecessary peripherals removed, no monitors or USB devices

At the time of writing I've waited about 30 minutes for the RasPi to finish, with no success.

UPDATE: 
If I run the same operations on my desktop (i7 6700K) with Raspbian in a chroot (qemu-user), vim-runtime also takes a couple of minutes to complete and I see a lot of io-wait during that time. So it does seem unpacking this package is indeed very heavy (for whatever reason), but it still shouldn't make the RasPi completely inoperable for 30+ minutes, IMHO. 
Like I mentioned before, several other packages (like apt itself) are also affected. System updates become impossible like this.

**Comment by michaelstoops** [comment] 2016-02-08 18:14
UPDATE: I have found a bad SD card reader in my system, which I suspect to be the cause of this and other symptoms.

I am experiencing a similar issue, with additional symptoms.

Steps to reproduce are the same as lhartvik's original post, but after rebooting, the /etc/sudoers file is messed up. I can't sudo for anything, can't even reboot without CTRL+ALT+DEL or unplug.

I'm using the Raspbian Lite 2015-11-21 image, have seen it manifest a number of times on different hardware, and on the "full" Raspbian image as well.

**Comment by Ruffio** [comment] 2016-08-17 19:39
@lhartvik has your issue been resolved? If so, please close this issue. Thanks.

**Comment by Ruffio** [comment] 2016-08-17 19:40
@lhartvik has your issue been resolved? If so, please close this issue. Thanks.

**Comment by Ignush** [comment] 2016-10-29 22:41
I have the same problem, same goes for installing gnome-user-guide has anyone solved the issue?

**Comment by XECDesign** [comment] 2016-10-29 22:54
This is just how dpkg works when the package has a lot of files. Many resources online point to eatmydata or enabling the unsafe IO option to speed it up, but having profiled dpkg, most of the time is spent in the hashing function and nothing else makes much of a difference.

**Closed as completed** 2017-03-29 06:16 UTC

**Comment by simonachmueller** [comment] 2017-11-09 21:37
I faced to exactly same problem, but on installing python packages, on unpacking step. Solved with using more powerful power supply (2 amps).
