### ISSUE TITLE
Please enable CONFIG_BLK_DEV_IO_TRACE

### ISSUE THREAD

**Issue by vpelletier** [raspberrypi/linux#702] opened 2014-10-06 01:41 UTC
Block io tracing feature would help reduce SD wear by being able to know where writes happen and why (=what processes cause these writes). This is especially useful to see how often a given block is written to, such as fs superblocks.

**Comment by popcornmix** [comment] 2014-10-07 16:58
I think this needs some testing. Enabling this option also enables:

```
CONFIG_TRACEPOINTS=y
CONFIG_NOP_TRACER=y
CONFIG_EVENT_TRACING=y
CONFIG_CONTEXT_SWITCH_TRACER=y
CONFIG_TRACING=y
CONFIG_GENERIC_TRACER=y
CONFIG_BINARY_PRINTF=y
```

I used to enable more tracing options in the kernel until I discovered it cost us about 10% in performance.
If you want this in you'll need to build the kernel with it enabled and provide some evidence that doesn't cause any performance regressions (e.g. measure "free -h" and perhaps nbench before and after the change).

**Comment by vpelletier** [comment] 2014-10-17 20:26
Sadly, I'm not near that Pi anymore (and don't want to take the risk of it not booting) and don't have aniother at hand, so I cannot run tests. It's an interesting point nevertheless, that enabling debug/trace features could slow down execution.
The load from my use is very light so I could easily live with the overhead.

**Comment by Ruffio** [comment] 2016-08-10 19:42
@vpelletier has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by JamesH65** [comment] 2017-05-17 14:27
Closing due to lack of activity. Reopen if you feel this issue is still relevant.

**Closed as completed by JamesH65** 2017-05-17 14:27 UTC
