### ISSUE TITLE
Kernels >= 3.10: w1_gpio destroys i2c bus 0 (raspicam doesn't work anymore)

### ISSUE THREAD

**Issue by crashmaster1** [raspberrypi/linux#435] opened 2013-11-18 03:43 UTC
Since kernel versions >=3.10 "w1_gpio" became a showstopper for i2c bus 0 users, f.e. raspicam needs that!

It can be simply checked:
- boot without loading the w1_gpio module
- check i2c bus 0 ("i2cdetect -y 0"), you see lots of dashes, that's fine
- now load w1_gpio (modprobe w1_gpio)
- check i2c bus 0 again: all dashes have gone and you get a lot of numbers in ascending order :(
- f.e. your raspicam will hang now (it uses i2c bus 0)

This happens with the latest official kernel for RPi (= 3.10.19-1) and newer versions.

Switching back to the previous version 3.6.11-18 works fine (without destroying i2c bus 0).

**Comment by JamesH65** [comment] 2013-11-18 20:57
I think this is a dupe of #434

**Comment by crashmaster1** [comment] 2013-11-19 02:40
I didn't think so because it also affects the _official_ kernel 3.10.x.

**Comment by popcornmix** [comment] 2013-11-20 22:41
I've had a quick look and can reproduce the problem.
The problem is that the 1-wire module overwrite the gpio function selection for the I2C pins.
Before 1-wire is loaded *0x20200000 = 0x48024 and I2C works (GPIO0 and GPIO in I2C alt function)
After 1-wire is loaded *0x20200000 = 0x48921 and I2C fails (GPIO0 is set to an output)

No idea yet why that happens yet, but that explains why I2C (and camera) stops working.

**Comment by crashmaster1** [comment] 2013-11-21 00:48
Thanks popcornmix.

A workaround is to load <b>first the 1wire modules</b> and afterwards the i2c modules. 
I2c initialization overwrites the 1wire quirks for bus 0, cam and w1 sensors work fine now.

**Comment by popcornmix** [comment] 2013-11-21 15:02
@crashmaster1 
Are you aware of where in the code register 0x20200000 gets written when 1-wire is loaded?
I noticed that the 3.10 1-wire driver does some pin-muxing calls that 3.6 didn't do, but I assumed we have no pin muxing driver, so that would be a no-op.

**Comment by crashmaster1** [comment] 2013-11-21 23:15
Sorry, i'm not aware of that.

**Comment by chtitux** [comment] 2013-12-19 00:03
The workaround of @crashmaster1 DOES work (thank you !), at least on `3.10.24+` kernel.
If if does not work, verify that : 
1. The `i2c-bcm2708` **is** blacklisted in your `/etc/modprobe.d/raspi-blacklist.conf`
   
   <pre># blacklist spi and i2c by default (many users don't need them)
   blacklist spi-bcm2708
   blacklist i2c-bcm2708</pre>
2. The modules are **in this order** in your `/etc/modules` 
   
   <pre>w1-gpio
   w1-therm
   i2c-bcm2078
   i2c-dev
   </pre>

**Comment by dkossman** [comment] 2013-12-20 18:34
sorry if this is a dumb question - trying to work around this issue - i'm using the rpi camera, 1-wire temp probes, and i2c (for running an lcd display, AD converter, etc.).  I assume that if i blacklist spi and i2c that they'll stop working?

my /etc/modules currently looks like this:

w1-gpio pullup=1
w1_therm
snd-bcm2835
spi-bcm2708
i2c-bcm2708
i2c-dev

and raspi-blacklist.conf:

#blacklist spi-bcm2708
#blacklist i2c-bcm2708

thanks

**Comment by crashmaster1** [comment] 2013-12-20 22:43
You should not change your blacklist but in etc/modules try this order:

w1-therm
w1-gpio pullup=1
i2c-dev
i2c-bcm2708
spi-bcm2708
snd-bcm2835

**Comment by dkossman** [comment] 2013-12-20 23:03
thanks - made that change and restarted, but unhappily I'm still getting the same error.  I've updated to the latest using apt-get update, apt-get upgrade, and rpi-update.  Any suggestions?

pi@raspberrypi ~ $ /usr/bin/raspistill -v -ex auto -mm backlit -w 1024 -h 768 -t 0 -o test.jpg                    

raspistill Camera App v1.3.5

Width 1024, Height 768, quality 85, filename test.jpg
Time delay 0, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Run forever

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'backlit', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

**Comment by crashmaster1** [comment] 2013-12-21 02:25
At first I've also got the ENOSPC failure. In my case I commented all "cma_" params i had made in "config.txt" and it helped. Probably you don't have them, but in my opinion you should look there to find out proper values for memory usage and you should have the latest firmware installed.

**Comment by dkossman** [comment] 2013-12-21 03:34
Thanks, I don't have any "cms_" params in config.txt - i am pretty sure that i've never edited that file.  the only uncommented lines are:

start_x=1
gpu_mem=128

when i run "i2cdetect -y 0" the output shows increasing numbers instead of dashes.  

By the way, if the camera uses i2c bus 0, i'm a bit confused about how we can use the suggested workaround above, when changing the order in /etc/modules doesn't work:

```
  "The i2c-bcm2708 *is* blacklisted in your /etc/modprobe.d/raspi-blacklist.conf"
```

can anyone explain?  or did i misunderstand?

thanks
Don

**Comment by dkossman** [comment] 2013-12-21 04:07
OK.  i uncommented "blacklist i2c-bcm2708" in /etc/modprobe.d/raspi-blacklist.conf and now it appears that everything works (i2c, the 1-wire temperature probes, and the pi camera).  I assume I misunderstood your suggestion above, and I'm going to leave well enough alone :-).  Thanks for your help!

 pi@raspberrypi ~ $ cat /etc/modprobe.d/raspi-blacklist.conf
 # blacklist spi and i2c by default (many users don't need them)

 #blacklist spi-bcm2708
 blacklist i2c-bcm2708

**Comment by smillerk2** [comment] 2013-12-22 19:41
@dkossman I'm experiencing the same issue as you and have the same settings but am still getting the "mmal: mmal_vc_component_enable: failed to enable component: ENOSPC" error when calling raspistill.

Any ideas?

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.10.24+ #614 PREEMPT Thu Dec 19 20:38:42 GMT 2013 armv6l GNU/Linux

pi@raspberrypi ~ $ cat /etc/modprobe.d/raspi-blacklist.conf
#blacklist spi-bcm2708
blacklist i2c-bcm2708

pi@raspberrypi ~ $ cat /boot/config.txt
...
start_x=1
gpu_mem=128
disable_camera_led=1
smsc95xx.turbo_mode=N

pi@raspberrypi ~ $ cat /etc/modules
snd-bcm2835

**Comment by dkossman** [comment] 2013-12-22 21:28
not sure.  I'm on the same kernel as you. I'm using a couple of 1-wire temperature probes and i2c (for an A/D converter and LCD display, as well as the rpi camera).  for what its worth, my /etc/modules looks like this:

 w1-therm
 w1-gpio pullup=1
 i2c-dev
 i2c-bcm2708
 spi-bcm2708
 snd-bcm2835

Also, I don't have the "disable_camera_led" or smsc95xx" lines in config.txt

Don

**Comment by ghost** [comment] 2013-12-24 21:35
Same here, for some reason the workaround (loading w1 modules first) doesn't help for me, it only works if I never load them at all (which means no 1-wire devices can be used). This is on kernel 3.10.25+ by the way (I saw the default raspbian image still comes with 3.10.24+). Maybe that's the difference? I just updated today with apt-get.

I did check that i2c-bcm2708 is indeed blacklisted so it doesn't autoload. Very strange.

**Comment by crashmaster1** [comment] 2013-12-25 04:34
Relational to the last comments it's really strange but a bug is a bug and my workaround not a guarantee for success for everybody ;) Anyways i'm wondering because i use this workaround on 4 RPi's needing 1wire and cam (i2c) together - not less but also not more. For me it works.
Why blacklist a module which is really needed? I'm also just wondering about that but indeed a bug is a bug. ;)

**Comment by martinohanlon** [comment] 2014-01-02 18:55
I don't know if this will help anyone, but I have found that this bug is only prevalent in 2nd revision Pi's. 1st Revision Model B's aren't affected.

**Comment by Elucidation** [comment] 2014-01-08 10:46
**(Success Update below)**
Sadly workaround isn't working for me either. I have the watchdog daemon running if that affects anything.

Rpi version B, firmware #622 (most recent update as of 5:44 AM 1/8/2014)

/etc/modules

```
w1-gpio
w1-therm

bcm2708_wdog

snd-bcm2835

i2c-bcm2078
i2c-dev
```

Alternate configs tried:

```
w1-therm
w1-gpio pullup=1
i2c-bcm2078
i2c-dev
snd-bcm2835
bcm2708_wdog
```

and same with watchdog at the head.

blacklist.conf

```
# blacklist spi and i2c by default (many users don't need them)
blacklist spi-bcm2708
blacklist i2c-bcm2708
```

Also tried with spi-bcm2708 commented out, no luck.

I have the camera, a 1wire DS18B20 temp sensor, and a i2c humidity/temp sensor hooked up.to the rpi.

**Update (Next Day)**
Successfully got the workaround to work. Looks like I needed to add the spi-bcm2708 (sorry if that was a dumb revelation, I didn't realize)

/etc/modules

```
w1-therm
w1-gpio pullup=1
i2c-dev
i2c-bcm2708
spi-bcm2708
snd-bcm2835
bcm2708_wdog
```

/etc/modprobe.d/raspi-blacklist.conf

```
# blacklist spi and i2c by default (many users don't need them)
#blacklist spi-bcm2708
blacklist i2c-bcm2708
```

**Comment by smillerk2** [comment] 2014-01-20 23:45
@dkossman - I was able to finally figure out the ENOSPC issue on 3.10.27. I've been using Motion as a local service with my camera and this was configured to call raspistill every second. My cgi-bin script was calling raspistill with -t 0 and this was causing the camera to hang and return the dreaded ENOSPC error (reboot required to clear). 

At some point between 3.6 and 3.10, raspistill must have changed the use of -t. On 3.6 with -t 0 the camera would take a picture and then release resources, on 3.10 it waits indefinitely and subsequent calls generate the error.

Changing the raspistill call to pass in a small value for the time out (e.g -t 10) fixed the issue for me.

**Comment by dkossman** [comment] 2014-01-21 00:12
@smillerk2 - thanks for following up.  I'd noticed the same issue with -t in my raspistill calls (from a php web script) and corrected it at around the same time i made some other changes, but didn't connect the dots...

**Comment by JamesH65** [comment] 2014-01-21 14:52
The change to -t 0 running indefinitely was some months ago. Note that values of -t of less than about 500ms are likely to result in images with bad exposure values. The system needs 500ms or more to get started and receive enough frames in to work out the required exposure. -t 10 will often result in badly exposed images.

Note also that the 'reboot required' issue has also been recently fixed. Now, any second instantiation of the camera whilst it is already running will simply drop out, and not lock up the firmware.

**Comment by ttresanti** [comment] 2014-02-27 10:17
I changed the /etc/modules and /etc/modprobe.d/raspi-blacklist.conf as described before, but pi camera still doesn't works with the error "mmal: Received unexpected camera control callback event, 0x4f525245"

Follow the command line

uname -a
Linux raspberrypi 3.10.32+ #646 PREEMPT Wed Feb 26 16:47:04 GMT 2014 armv6l GNU/Linux

raspistill -v -ex auto -mm backlit -w 1024 -h 768 -t 0 -o test.jpg

raspistill Camera App v1.3.6

Width 1024, Height 768, quality 85, filename test.jpg
Time delay 0, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Run forever

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'backlit', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
Camera component done
Encoder component done
Starting component connection stage
Connecting camera preview port to video render.
Connecting camera stills port to encoder input port
Opening output file test.jpg
Enabling encoder output port
Starting capture 1
mmal: Received unexpected camera control callback event, 0x4f525245

**Comment by myusernamejeep** [comment] 2014-04-08 17:57
I have the same problem.

pi@raspberrypi ~ $ raspistill -o a1.png -v

raspistill Camera App v1.3.7

Width 2592, Height 1944, quality 85, filename a1.png
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No

Capture method : Single capture
Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000

Camera component done
Encoder component done
Starting component connection stage
Connecting camera preview port to video render.
Connecting camera stills port to encoder input port

Opening output file a1.png
Enabling encoder output port
Starting capture 0

mmal: Received unexpected camera control callback event, 0x4f525245

**Comment by keendog** [comment] 2014-04-23 18:19
So this seems to have just started happening on my camera as well. Same mmal: Received .... error at the bottom of running a raspistill -v

my i2c-0 table only has the address 36 populated. Everything else is dashes. I am using a grid-eye i2c on i2c-1 and that seems to work.  

@myusernamejeep did you get anywhere with your camera?

**Comment by LabinskiyKN** [comment] 2014-05-13 17:30
Hi there!
Seems to me, I found interesting way to fix the problem. I don't know, is this way correct, but... it works :)
So, I have RPi rev. B 2.0 with 1-wire DS18B20, i2c BMP085 pressure sensor and raspicam.
when  I try to use 

pi@raspberrypi ~ $ raspistill -v -o test.jpg

sometimes I have an error: ENOSPC.
In this moment when I run 

pi@raspberrypi ~ $ sudo i2cdetect -y 1

I can see all ports free except one where the pressure sensor is used. But 

pi@raspberrypi ~ $ sudo i2cdetect -y 0 

shows me all ports busy...
Seems to me, the problem is in port P5 on RPi rev. B 2.0 - this is a second i2c: i2c-0 which is used with the raspicam and we have our problem.
Because of not using i2c-0 on P5 port I can turn off that port with the help of hipi-i2c utility: 

pi@raspberrypi ~ $ sudo hipi-i2c e 0 0

After that 

pi@raspberrypi ~ $ sudo i2cdetect -y 0

shows all free ports and I can use my raspicam...

**Comment by ajlennon** [comment] 2014-05-26 18:50
If this relates to w1-gpio and particularly the I2C bus on GPIO0 then it may relate to the issue I believe I discovered with the RPi BSP providing GPIO0 as a pullup pin to w1-gpio #601. I believe I have a fix in #602

**Comment by hilmanshini** [comment] 2014-07-26 02:41
How is it now? is it solved yet?
me either not works. 2 month struggling this, 

i have tried new rpi and new camera with following the instruction,  but still rpi camera not working.

**Comment by joshhankins** [comment] 2014-08-11 13:42
@crashmaster1 Please can you explain the steps required in order to fix my raspberry pi camera in a more simple way as i have just started programming and using the pi. Thanks for your help - much appreciated!

**Comment by crashmaster1** [comment] 2014-08-11 14:43
@gecko: Sorry, i can't because i'm using Arch on my RPi's (not Raspbian). I think, it's better you ask for this in the Raspberry forum.

**Comment by JamesH65** [comment] 2014-08-11 18:29
Indeed, please use the forums to get advice and help for this sort of
thing. The camera is known to work with the latest boards and
firmware/kernel.

**Comment by kimbongzo** [comment] 2014-09-17 02:50
Solution~

Open /etc/modules -> sudo nano /etc/modules

and below add two #

snd-bcm2835
i2c-dev
#w1-gpio
#w1-therm
lirc_dev
lirc_rpi gpio_out_pin=7

and reboot. then GPIO Collision deleted.

**Comment by bootor** [comment] 2014-09-21 18:33
... and 1-wire will stop working...

**Comment by popcornmix** [comment] 2014-09-22 15:12
@bootor 
If you want to use 1-wire with a camera you need to set the GPIO pin to use. E.g. add to cmdline.txt

```
bcm2708.w1_gpio_pin=16
```

You can also code it in /etc/modules
w1-gpio-gpiopin=16

Problem is by default w1 modules uses GPIO4 which is needed by camera.

**Comment by GertjanvanhetHof** [comment] 2016-03-26 20:03
I had the same problem and I found probably the cause because I was able to reproduce it.
For me it was a hardware problem. One of the wires on de flex cable (from raspberry to camera module) was broken. 
When I bow the cable the above problem was shown. This was because the connection was broken.
When I put the cable straight, the camera was working correctly.
I think it is the most left wire when camera is pointing to me.

**Comment by Ruffio** [comment] 2016-08-10 10:56
@crashmaster1 has this issue been resolved? If yes, then please close this issue.

**Closed as completed** 2016-08-10 12:55 UTC

**Comment by kenxausten** [comment] 2017-09-15 05:30
I am still encounter this issue. how should i do to solve this issue?
**pi@raspberrypi:~$ raspistill -o 1.jpg -v**

raspistill Camera App v1.3.11

Width 3280, Height 2464, quality 85, filename 1.jpg
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Single capture

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

**pi@raspberrypi:~$ cat /etc/modprobe.d/raspi-blacklist.conf** 
# blacklist spi and i2c by default (many users don't need them)
#blacklist spi-bcm2708
#blacklist i2c-bcm2708
**pi@raspberrypi:~$ uname -a**
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
**pi@raspberrypi:~$ cat /etc/modules**
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.

w1-therm
w1-gpio pullup=1
w1-gpio-gpiopin=16
bcm2708.w1_gpio_pin=16
i2c-bcm2078
i2c-dev
snd-bcm2835
bcm2708_wdog

**Comment by pelwell** [comment] 2017-09-15 08:15
You've got the latest firmware but your configuration was obsoleted 2 years ago with the switch to Device Tree. Try this:
1. Remove everything from `/etc/modules` except this:
```
i2c-dev
```
2. Delete /etc/modprobe.d/raspi-blacklist.conf - you shouldn't need it.
3. Enable the camera using raspi-config:
```
sudo raspi-config
# Open Interfacing Options
# Select Camera
# Choose Yes to enable the camera
```
This will add `start_x=1` and `gpu_mem=64` to `/boot/config.txt`.

3. If you are using a onewire device such as a DS18B20 (you don't say) then edit `/boot/config.txt` and add this line:
```
dtoverlay=w1-gpio,gpiopin=16,pullup
```
substituting your own pin number. Note that if your wiring to the onewire device includes a 3.3V line (which I recommend if you can), i.e. if it isn't using the phantom powering feature, then you just need:
```
dtoverlay=w1-gpio,gpiopin=16
```
4. Reboot.
