### ISSUE TITLE
Bluetooth D-Bus config is missing a policy section that enables root-less access

### ISSUE THREAD

**Issue by WayneKeenan** [raspberrypi/linux#1494] opened 2016-05-26 10:30 UTC
In the Feb'16 Raspbian release it was possible to use the bluetooth DBus API without having to be root or using `sudo`.  
The latest Raspbian (May'16) has a `policy` section missing from `/etc/dbus-1/system.d/bluetooth.conf`

``` xml
<!-- allow users of bluetooth group to communicate -->
<policy group="bluetooth">
    <allow send_destination="org.bluez"/>
</policy>
```

More info in a follow-up here https://github.com/ukBaz/python-bluezero/issues/30

**Comment by Ruffio** [comment] 2017-01-26 09:36
@pelwell Do you know if this (removal of policy) is by design?

**Comment by pelwell** [comment] 2017-01-26 09:48
This is a Raspbian question rather than a kernel issue, but since it's been sitting here for so long:

I doubt it would have been removed intentionally by us, but @XECDesign and @spl237 might know otherwise.

**Comment by spl237** [comment] 2017-01-26 10:31
Looking at the current release, the policy section you refer to above is present in bluetooth.conf.

**Comment by Ruffio** [comment] 2017-02-05 11:20
@WayneKeenan  this has been resolved? Right?

**Comment by JamesH65** [comment] 2017-05-18 11:52
Closing this issue as questions answered/issue resolved.

**Closed as completed by JamesH65** 2017-05-18 11:52 UTC
