### ISSUE TITLE
RFID-RC522 working for for raspberry pi 3 model

### ISSUE THREAD

**Issue by namesisxna** [raspberrypi/linux#1630] opened 2016-09-06 07:33 UTC
RFID-RC522 does not work with the latest release of Jessie(2016-05-10) neither with release of Jessie(2016-03-18).If I type lsmod after enabling spi I get the spi_bcm2825 for both the version. I am using Raspberry Pi 3 model B. I can confirm this.. In /boot/config.txt I have the following
dtparam=spi=on and If I go into the /dev folder and type "ls"
I see spidev0.0 and spidev0.1
I have tried with 
device_tree_param=spi=on
dtoverlay=spi-bcm2708 in /boot/config.txt
I have used the following reference 
https://github.com/mxgxw/MFRC522-python
http://raspmer.blogspot.in/2015/07/how-to-use-rfid-rc522-on-raspbian.html
https://www.sunfounder.com/wiki/index.php?title=How_to_Use_an_RFID_RC522_on_Raspberry_Pi

and implemented it perfectly but still not enough fortunate to get the UUID from RC522.
Stick with it for 2 weeks. Need ur valuable advice please help........

**Comment by pelwell** [comment] 2016-09-06 08:07
This is a duplicate of https://github.com/raspberrypi/linux/issues/1547.

**Closed as completed by pelwell** 2016-09-06 08:07 UTC
