### ISSUE TITLE
Boot sequence hangs after hub detection of model B with fiq_fix_enable=0 in rpi-3.9.y

### ISSUE THREAD

**Issue by KrfVan** [raspberrypi/linux#355] opened 2013-08-12 20:07 UTC
fiq_fix_enable=0 causes the rpi model B to hang just after detection of the intenal usb 3 port hub with the latest commits of rpi-3.9.y (cc6163c1d8). It still worked on 1fe837e

**Comment by P33M** [comment] 2013-08-12 21:11
Edit: What does dmesg say? (or at least the console output - photograph the screen if you can't get a serial port data dump)

**Comment by KrfVan** [comment] 2013-08-12 21:52
@P33M Here is the screen photograph, the rpi just hangs there. I also have fiq_split_enable=0. Everything goes well when fiq_fix_enable=1 and fiq_split_enable=1, but that's not what I want.
![fiq_fix_disabled](https://f.cloud.github.com/assets/4789699/951034/6bf7bbf0-0399-11e3-84b5-6545145df3f0.jpg)

**Comment by P33M** [comment] 2013-08-12 22:06
Hm. That's odd - USB is actually working fine and manages to get the device descriptor for the smsc chip, but then breaks for some reason.

Do you have any devices plugged into the USB ports?

**Comment by KrfVan** [comment] 2013-08-13 07:35
@P33M I've tested both with and without devices connected, same behavior. I can get an extra message when I have an usb device attached and unplug at the moment of the hang:
INFO: rcu_preempt detected stalls on CPUs/tasks: {} (detected by 0, .....)
INFO: stall ended before state dump start

Then it's hanging again.

**Comment by P33M** [comment] 2013-08-13 10:52
I can replicate this with 3.6 and 3.9 - but there are a lot of commits between those two you posted.

I will do a bisect.

**Comment by KrfVan** [comment] 2013-08-13 15:06
@P33M I've tested with db4fad7 and the issue is already there. So it's probably caused by something in the fiq_split implementation?

**Comment by KrfVan** [comment] 2013-08-21 21:03
I've solved this issue, the SOF interrupt is cleared only in the FIQ code.  So fiq_fix_enable=0 also disables the clearing of the SOF interrupt. The following patch (for the latest 3.9.y branch: 56ec798cbe) reenables the clearing of the SOF interrupt code when fiq_fix_enable=0:

```
diff --git a/drivers/usb/host/dwc_otg/dwc_otg_hcd_intr.c b/drivers/usb/host/dwc_otg/dwc_otg_hcd_intr.c
index 19abea0..78172ea 100644
--- a/drivers/usb/host/dwc_otg/dwc_otg_hcd_intr.c
+++ b/drivers/usb/host/dwc_otg/dwc_otg_hcd_intr.c
@@ -742,8 +742,10 @@ int32_t dwc_otg_hcd_handle_sof_intr(dwc_otg_hcd_t * hcd)
    }

    /* Clear interrupt */
-   //gintsts.b.sofintr = 1;
-   //DWC_WRITE_REG32(&hcd->core_if->core_global_regs->gintsts, gintsts.d32);
+   if (!fiq_fix_enable) {
+       gintsts.b.sofintr = 1;
+       DWC_WRITE_REG32(&hcd->core_if->core_global_regs->gintsts, gintsts.d32);
+   }

    return 1;
 }
```

**Comment by P33M** [comment] 2013-08-21 21:47
I will test this tomorrow. The root of the issue is the way that we deal with FIQ->IRQ interactions generically - basically instead of the IRQ reading the actual hardware registers we "fake" the ones that the FIQ deals with. This is to ensure that the FIQ can operate independently of the IRQ - i.e. receive and acknowledge interrupts from the hardware and run independently of the IRQ.

I had been sniffing around the myriad interrupt handlers as a sort-of fix, but had nothing concrete as of yet.

Cookie for you if it works!

**Comment by P33M** [comment] 2013-08-28 09:21
This looks like a viable fix to me. Booting now successful and back to 8k interrupts a second.

Can you submit a PR?

**Comment by P33M** [comment] 2013-12-03 21:59
Change is now in kernel - closing

**Closed as completed by P33M** 2013-12-03 21:59 UTC
