### ISSUE TITLE
Waveshare 7inch DSI LCD (C) - doesn't work

### ISSUE THREAD

**Issue by miklosakos** [raspberrypi/linux#5576] opened 2023-08-15 23:51 UTC
### Describe the bug

The open source reverse engineered driver doesn't drive the Waveshare 7inch DSI LCD display, the official ones aren't a suitable option.
@6by9 worked on the driver, according to them it should work but the backlight never turns and the touch doesn't work either.

### Steps to reproduce the behaviour

Update to latest raspberry pi firmware, enable the required dtoverlays.

### Device (s)

Raspberry Pi 4 Mod. B

### System

`cat /etc/rpi-issue`

```
Raspberry Pi reference 2023-05-03
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7c750947a959fb626a70c09fd17c65815df192ac, stage2
```

`vcgencmd version`

```
Aug 10 2023 15:33:38
Copyright (c) 2012 Broadcom
version 03dc77429335caee083e22ddc8eec09c07f12a7a (clean) (release) (start)
```

`uname -a`

```
Linux raspberrypi 6.1.45-v8+ #1671 SMP PREEMPT Fri Aug 11 14:49:25 BST 2023 aarch64 GNU/Linux
```

### Logs

[dmesg.txt](https://github.com/raspberrypi/linux/files/12353775/dmesg.txt)
[i2cdetect.txt](https://github.com/raspberrypi/linux/files/12353779/i2cdetect.txt)

**Comment by 6by9** [comment] 2023-08-16 09:32
Duplicate of https://forums.raspberrypi.com/viewtopic.php?t=355034 by the sounds of it.
The 7inchC display connects to i2c-1 by default, so use ```dtoverlay=vc4-kms-dsi-waveshare-panel,7_0_inchC,i2c1``

Your dmesg log shows
```
[    9.328105] ws_touchscreen 10-0045: I2C write failed: -5
[    9.328303] ws_touchscreen 10-0045: I2C write failed: -5
[    9.328477] ws_touchscreen 10-0045: I2C write failed: -5
```
i2c-10 is the I2C bus up the FFC.

**Comment by miklosakos** [comment] 2023-08-16 13:56
Thank you this fixed it, I have another issue I would like to mention: when the system gets restarted / shut down, the backlight never gets turned off so the display will have this full white fill out that only goes away if the pi is power cycled fully.
![IMG_2656](https://github.com/raspberrypi/linux/assets/8452012/8c4965e9-ee2e-4b96-943f-615d77257172)
![IMG_2657](https://github.com/raspberrypi/linux/assets/8452012/62c8020b-a9c7-44f8-b853-bac5d9e89d28)
![IMG_2658](https://github.com/raspberrypi/linux/assets/8452012/867dfd2d-64d9-4a44-94b9-8e6a14bdcab7)

**Comment by bou6** [comment] 2023-08-18 08:04
@miklosakos, You need to put the power pin to low, and then the display will switch off.

**Comment by 6by9** [comment] 2023-08-22 12:01
> I have another issue I would like to mention: when the system gets restarted / shut down, the backlight never gets turned off so the display will have this full white fill out that only goes away if the pi is power cycled fully.

Is that any different from the Waveshare drivers? I suspect not, and there is very little that can be done about it.
Linux doesn't tell the graphics stack that it's shutting down, therefore the display drive is just removed. For HDMI that generally results in the display sleeping. For DSI it is down to the panel implementation, and many will end up just fading to white.

**Comment by miklosakos** [comment] 2023-08-25 19:42
> Is that any different from the Waveshare drivers?

Yes.
> I suspect not, and there is very little that can be done about it.

The waveshare driver turns the display off properly when the system gets shut down / rebooted.

**Comment by 6by9** [comment] 2023-08-30 14:56
I don't have a 7" Waveshare panel. The 2.8", 10.1", and 7.9" all appear to shut off cleanly, so I can't debug with those.
If anyone else with a 7" panel wishes to analyse it to see how it achieves powering the backlight off, then PRs are welcome.

The open source drivers exposes the backlight control through the standard Linux backlight API. Systemd should be able to do the right thing via a suitable file in ```/etc/systemd/system/poweroff.target.wants```. There is already one in there for the (old) Pi 7" display as ```rpi-display-backlight.service```. 

For the Waveshare panel with open drivers, the contents wants to be along the lines of:
```
[Unit]
Description=Turns off Waveshare display backlight on shutdown/reboot
ConditionPathIsDirectory=/proc/device-tree/soc/i2c0mux/i2c@1/panel_disp1@45
DefaultDependencies=no
Before=umount.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/bin/echo 1 > /sys/class/backlight/10-0045/bl_power'

[Install]
WantedBy=reboot.target halt.target poweroff.target

```
Same thing in ```/etc/systemd/system/reboot.target.wants```, and ```/etc/systemd/system/halt.target.wants```.

Pretty much the same thing wants to be added for the Pi 7" panel when using DRM drivers, so it is likely that they will get shipped with Raspberry Pi OS at some point. As Waveshare used the same I2C address as the Pi 7" panel, it may just work for that too.

Then again with the Waveshare 7" panel using i2c-1 rather than i2c-10, that scuppers things. For that one that paths are going to be
```
[Unit]
Description=Turns off Waveshare display backlight on shutdown/reboot
ConditionPathIsDirectory=/proc/device-tree/soc/i2c@7e804000/panel_disp1@45
DefaultDependencies=no
Before=umount.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/bin/echo 1 > /sys/class/backlight/1-0045/bl_power'

[Install]
WantedBy=reboot.target halt.target poweroff.target
```

Do note that this will only turn the backlight off. The LCD element will still be going white, you just won't have the illumination behind it.

**Comment by 6by9** [comment] 2023-08-30 14:57
Closing as the original issue is resolved (use i2c-1 rather than i2c-10).
Backlight needs more information from others, and should be a separate issue rather than being combined with this one.

**Closed as completed by 6by9** 2023-08-30 14:57 UTC
