### ISSUE TITLE
libgphoto2 / libusb access to cameras works only once

### ISSUE THREAD

**Issue by msmeissn** [raspberrypi/linux#103] opened 2012-09-05 13:02 UTC
Hi,

I am receiving bugreports from various sources, that libgphoto2 / libusb based access to remote control cameras
only works once.

After the first (working) access, the USB device no longer responds to writes, it is unclear if is stalled somehow or
some other USB problem exists.

This is be specific to the Raspberry PI.

Usually only USB bulktransfers are done, but USB interrupts transfers might also have played a role.

**Comment by DAFlippers** [comment] 2012-09-06 08:15
Are you using Libusb_interrupt_transfer to read the frames?

David

**Comment by msmeissn** [comment] 2012-09-06 08:34
Not sure if libusb 0.x or libusb 1.x is in use, but basically yes.

(libusb 1.x code is like:
        ret = libusb_interrupt_transfer (port->pl->dh, port->settings.usb.intep,
                             (unsigned char*)bytes, size, &curread, timeout);
)

**Comment by DAFlippers** [comment] 2012-09-06 09:48
I have reported LIBUSB-1.0  interrupt _transfer issue already: 
https://github.com/raspberrypi/linux/issues/79#issuecomment-8203702

The calls do not return data although data is read(/written) from(/to) the USB.

David

**Comment by ghollingworth** [comment] 2012-09-20 18:15
Was this effected by the recent changes to reduce NAK overheads?  I saw a marked performance increase in interrupt transfers with this change.

**Comment by drott** [comment] 2013-02-11 01:55
@ghollingworth - since I tried this with the latest kernel in https://github.com/raspberrypi/linux/issues/218 the response to your question would be no, no change.

**Comment by drott** [comment] 2013-02-11 01:56
@msmeissn The issue happens in both cases, no matter whether gphoto2 is linked with libusb 0.1 or 1.0.11.

**Comment by ghollingworth** [comment] 2013-08-22 09:10
Many changes in USB recently, retry, reopen if still broken

**Comment by drott** [comment] 2013-08-22 09:17
@ghollingworth alright - saw the committs in dwc_otg, will try again soon, thanks.

**Comment by ghollingworth** [comment] 2013-08-26 07:44
Seems the issue is still occurring with latest changes to USB, any idea how to reproduce the problem?  Can it be done with a Canon D50?

**Comment by drott** [comment] 2013-08-26 07:50
I would assume it's rather independent of the camera model. #218 has the reproduction steps.
When running 
$ strace gphoto2 --summary
twice, the second time the trace shows gphoto2 running into a loop retrying the USBDEVFS_REAPURBNDELAY ioctl.

Same happens basically when you try any larger gphoto usb operation, for example --list-files.

**Comment by msmeissn** [comment] 2013-08-26 08:45
There is also a bug in libgphoto2 versions before 2.5.2 where we cleared stalls unconditionally ... which was wrong.

This might still happen here if libgphoto2 is still older.

**Comment by drott** [comment] 2013-08-26 19:56
@msmeissn Fixed with gphoto 2.5.2 indeed (still failed with 2.5.1). Awesome, thanks very much. I tested a few things, raw image downloads, tethered captures, all working.
 Out of curiosity, do you have the SVN revision with the fix? What was the root cause, how does the raspberry behave differently?

@ghollingworth I guess this issue can be closed again, then.

**Comment by msmeissn** [comment] 2013-08-26 21:12
http://sourceforge.net/p/gphoto/code/14268/

**Comment by P33M** [comment] 2013-09-20 15:16
Closing as fixed in 3rd party software.

**Closed as completed by P33M** 2013-09-20 15:16 UTC
