### ISSUE TITLE
3.6.y: Kernel panic "Unable to handle kernel NULL pointer" using bluetooth

### ISSUE THREAD

**Issue by cioban** [raspberrypi/linux#177] opened 2012-12-30 01:19 UTC
I'm trying to use the asterisk chan_mobile with rpi-3.6.y kernel and I got a kernel panic after bluetooth connection :(
"Unable to handle kernel NULL pointer dereference at virtual address 00000000"
See the attached image.

I'm using latest 3.6.y kernel and latest firmware.

Please help me.
Thanks
![IMG_20121229_225407](https://f.cloud.github.com/assets/546389/35560/51641e64-521e-11e2-8cd2-aaf0165df697.jpg)

**Comment by licaon-kter** [comment] 2012-12-30 18:08
Is this a custom compiled kernel? What did you modify? What bluetooth device?

**Comment by cioban** [comment] 2012-12-30 19:11
Is not a custom kernel. I just took  the kernel from the github and compiled...

I' m using "Cambridge Silicon Radio" bluetooth.

**Comment by popcornmix** [comment] 2012-12-30 22:20
So does stock kernel (from rpi-update) do the same thing?

**Comment by cioban** [comment] 2012-12-31 11:03
Stock kernel (3.6.11+) from rpi-update does the same thing.

**Comment by licaon-kter** [comment] 2012-12-31 12:06
Does it do this on every connection, say if it's connected _before_ powering up? What power source? You connect the bluetooth device directly in the Pi or via a hub? If a hub, a powered hub? Add more details...

**Comment by popcornmix** [comment] 2012-12-31 12:50
Is keyboard still reposonsive after painc? I'd like to see rest of call stack after the "more>" line.;
You should also be able to type dmesg from that panic prompt to see if there were any allocation failures logged.

**Comment by cioban** [comment] 2012-12-31 15:05
@licaon-kter 
I got the kernel panic in every connection.
I tried to use bluetooth device connected directly in the Pi and connected in a powered USB hub, and the kernel panic occurred in both cases.
I tried to use bluetooth device connected before power up and connecting after entire linux boot and the kernel panic occurred in both cases too.
I'm using a 5v 3A power supply and when I used the powered USB HUB I used another 5v 1A power supply just for the USB HUB.

@popcornmix 
The keyboard doesn't work after panic. I'll try to use serial console to get the stack and dmesg.

**Comment by cioban** [comment] 2013-01-10 23:39
Hi all,

I have used serial console and after panic I have access to KDB.
This is dmesg output: http://pastebin.com/ak0Baw2G

Sorry but I don't know how to use the KDB, what could I get beyond the dmesg?
Thanks

**Comment by popcornmix** [comment] 2013-01-11 15:46
Can you try rpi-update?
This has fixed some USB related memory courruption:
https://github.com/raspberrypi/linux/commit/0d4c64977ac8baceeaf979921fbdcff1aa84e204

**Comment by foocode** [comment] 2013-01-16 09:00
I too have issues with bluetooth causing kernel panics. Raspbian (freshly updated with apt-get + rpi-update) and have tried 3 different bluetooth devices and 3 different means of supplying power.

**Comment by DirtyJerz** [comment] 2013-01-16 15:23
I have the same problem with bluetooth devices causing panics. I believe it is knock off bluetooth adapters. I bought 4 from ebay for ~$1 each, too good to be true. they look like this http://b2b.santok.com/images/s-images/dlbtvitm.jpg . They all have the EXACT same MAC addresses. lsusb shows Cambridge Silicon Radio and when you open the dongle up it should say 'CSR' on the chip. It doesn't. I should also mention that I have the same problem on every other linux machine I try them with. All cause panics. What does your lsusb and hcitool dev output?

**Comment by cioban** [comment] 2013-01-21 11:37
@popcornmix I did the rpi-update and the panic still occurred

@DirtyJerz My bluetooth dongle is a "Cambridge Silicon Radio" but in my case I have it working on my laptop without any panic...

**Comment by heggink** [comment] 2013-03-27 18:07
Same here: using sma-spot to upload solar panel data to pvoutput.org. First used an old class1 BT dongle from linksys. Oops/lock happening every couple of days. Switched to newer ICIDU dongle yesterday (to get around these issues, BT class 2 device) but no joy :-(. Luckily I have the watchdog active to reboot automatically...

**Comment by dodger-one** [comment] 2013-07-02 06:35
I've exactly the same problem, there's any new about that bug?

**Comment by licaon-kter** [comment] 2013-07-02 07:10
any reason not to update to the _next_ branch via **sudo BRANCH=next rpi-update** ?

**Comment by foocode** [comment] 2013-07-02 07:16
I will try this in the next hour.

**Comment by dodger-one** [comment] 2013-07-02 07:37
I'm upgrading, I'll report asap.
But I'll not be able to provide any screenshot/coredumped cause I've not setted up the environment and I'm very far from the rpi :-P

**Comment by dodger-one** [comment] 2013-07-02 07:54
fuuuuu... It doesn't automatically restart >:-(

**Comment by foocode** [comment] 2013-07-02 08:09
Not fixed, device still locks up when bluetooth is used.

**Comment by dodger-one** [comment] 2013-07-02 18:54
![img_20130702_203933](https://f.cloud.github.com/assets/1517001/738545/94b412b2-e348-11e2-8734-c0cf50116378.jpg)
Mine also hungs after the upgrade:
<code>Linux raspterminal 3.9.8+ #486 PREEMPT Fri Jun 28 21:40:56 BST 2013 armv6l GNU/Linux</code>

**Comment by heggink** [comment] 2013-07-03 15:07
That begs the question whether the bluetooth fix was actually included in this release. According to this (http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=37265) this change may not have made it into the rpi kernel...

**Comment by heggink** [comment] 2013-07-03 15:09
https://github.com/raspberrypi/linux/pull/283 also indicating it's not incorporated.

**Comment by foocode** [comment] 2013-07-03 15:17
Great sleuthing, thanks. How do we\who do we pressure to get this fix pushed via rpi-update?

**Comment by ghollingworth** [comment] 2013-07-03 15:22
Have you submitted a pull request?

**Comment by asb** [comment] 2013-07-03 15:25
On 3 July 2013 16:17, foocode notifications@github.com wrote:

> Great sleuthing, thanks. How do we\who do we pressure to get this fix
> pushed via rpi-update?

No need for any pressuring, looks like #283 wants to be merged. It's
much easier to approve a merge when people can test the patch and
report it fixes the problem for them. After Dom asking, the submitter
has confirmed it fixes the problem for them. If anyone else has time
to compile the kernel with that fix and report their results that's
always helpful.

**Comment by foocode** [comment] 2013-07-03 15:51
Happy to help/test if I can - is there a recommend guide that I can follow?

**Comment by dodger-one** [comment] 2013-07-03 15:54
I'm looking into rpi 3.10.y kernel source and the patch it's partially applied.
It seems that only 1 part inside of  "net/bluetooth/l2cap_core.c" is not applied, but there are a couple of things that are different between the official linux kernel code and the rpi one...

**Comment by heggink** [comment] 2013-09-06 13:14
Any updates/progress from anyone?

**Comment by dodger-one** [comment] 2013-09-06 15:01
I investigate a bit more and the cause is a counterfeit usb-bluetooth dongle (the dx.com one).
The original one works without problems (unless that what I read).

**Comment by P33M** [comment] 2014-05-05 13:02
Bluetooth devices are reliable with fiq_fsm (and 3.12 has the upstream commit added).

**Closed as completed by P33M** 2014-05-05 13:02 UTC
