### ISSUE TITLE
Kernel bug in sound/arm/bcm2835-vchiq.c:186

### ISSUE THREAD

**Issue by haebler** [raspberrypi/linux#122] opened 2012-09-24 01:00 UTC
It seems there was a new bug introduced in the latest kernel build.

Error is as follows:
kernel BUG at sound/arm/bcm2835-vchiq.c:186!
Internal error: Oops - undefined instruction: 0 [#1] PREEMPT

[Screenshot](https://picasaweb.google.com/lh/photo/Susy7eADXQS56l9yG9VmtS1GpfdHyGtjmi50fNh38lk?feat=directlink)

I can somewhat reliably reproduce it by playing multiple mp3 files in sequence with mpg123.

This bug started showing up after updating to the latest version on 9/22. I have been playing mp3s with mpg123 like this for a while without any issues.

Playback is via 3.5mm audio jack while having an HDMI/DVI monitor connected.

**Comment by dozzman** [comment] 2012-09-24 09:42
I cant seem to reproduce this bug with mpg123. Do you have a command that I could run which causes this oops?

**Comment by haebler** [comment] 2012-09-24 13:11
Just calling mpg123 from a Python script via subprocess.Popen() it with some VBR MP3. No options. Here is the version of mpg123 - it is the latest in the package repo.

$ mpg123 --version
mpg123 20120622000000

I am using the arm192_start.elf for a 192/64 split.

**Comment by popcornmix** [comment] 2012-09-25 10:27
@haebler 
Can you post whatever is need to provoke the bug?
E.g. bash scripts and/or python code.
Ideally, confirm it fails with a freely available mp3 file.

**Comment by haebler** [comment] 2012-09-25 13:45
@popcornmix 
I will get you guys more details when I have some time this week. 

For now here is how this is invoked in a python script:

player = "/usr/bin/mpg123"

d = shelve.open(state_file)
song = "<some mp3 file based on input>"
...
d["pid"] = subprocess.Popen([player, song]).pid
d.sync()
d.close()

Nothing out of the ordinary, really.

Another possibly related item, I am calling amixer from .profile to set the volume

amixer -c 0 set PCM 4dB on

**Comment by popcornmix** [comment] 2012-09-28 12:18
I think this is the same issue:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=18369

It seems when calling audio from python, using snd-pcm-oss module, the sound driver gets called with a kernel allocated buffer rather than a user mode buffer.
The copy_from_user operation causes a panic.

There is a newer version of the vchiq code that does handle bulk transfers form kernel allocated buffers which we'll hopefully merge with soon.

**Comment by qmerge** [comment] 2012-09-28 13:01
I get this though a very different path.  It seems to be related to a fast close/open of the sound driver.
Was able to work around by adding >1 second delay to the open.
using playmp3list, occurs when changing directory between tracks.
100% repeatability for both bug and fix.

**Comment by popcornmix** [comment] 2012-11-28 15:51
I believe this is fixed in "next" fimware tree. See:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=19334&p=223173#p222362

I'd be interested if updating fixes this.

**Closed as completed** 2013-01-24 00:19 UTC
