### ISSUE TITLE
Kernel changes 3.10.25+ causes ALSA buffer underruns

### ISSUE THREAD

**Issue by w9ran** [raspberrypi/linux#561] opened 2014-04-13 02:02 UTC
This is to provide additional description of the problem noted by others related to ALSA recording and in my case, playback of audio stream from DVB-T dongle (RTL2832 device) which has worked fine until now.   Buffer underruns occur consistently and without regard to the audio streaming rate whenever CPU utilization is low.   Running any task that keeps the CPU busy results in perfectly smooth audio without interruptions.   Thus the problem seems to be related to a kernel change that affects latency or something when the CPU is allowed to be idle.    Symptoms are  unchanged with kernel version 3.10.36 as well.   

The RTL2832 dongle will stream raw sample via TCP at 2 mbps, so this doesn't seem to be USB related, but only occurs when piping audio samples at rates from 8 to 32 kpbs.

Others have reported that reverting back to  Rasbian 2013-07-26 which is said to be the latest build to have kernel 3.6.11+ cured the problem.

Bob

**Comment by popcornmix** [comment] 2014-04-13 10:42
Duplicate of https://github.com/raspberrypi/linux/issues/560

**Closed as completed by popcornmix** 2014-04-13 10:42 UTC
