### ISSUE TITLE
WIFI channels 12 and 13 not being recognized by Raspberry 3

### ISSUE THREAD

**Issue by blfuentes** [raspberrypi/linux#1355] opened 2016-03-20 11:20 UTC
Version 4.1.20 of firmware still doesn't recognize channels 12 and 13 in country zones where those should be available.

**Comment by popcornmix** [comment] 2016-03-20 11:31
This seems to be an upstream kernel issue. I believe if you update to 4.4. kernel with `sudo BRANCH=next rpi-update` then channels 12 and 13 are usable.

(but be aware that rpi-update is for testers and there may be regressions).

It is likely we will move to 4.4 kernel as a default soon (next week or so for master branch rpi-update with apt-get to follow) so that is the likely route to getting the higher channels.

**Comment by grigorig** [comment] 2016-03-22 14:24
I can confirm that channels 12 and 13 work with kernel 4.4.

**Comment by pelwell** [comment] 2016-03-22 14:42
Thanks for the confirmation.

**Comment by popcornmix** [comment] 2016-04-11 20:09
Latest rpi-update kernel is now 4.4 so shouldn't have this issue.

**Comment by JamesH65** [comment] 2017-05-18 09:43
Closing this issue as questions answered/resolved.

**Closed as completed by JamesH65** 2017-05-18 09:43 UTC
