### ISSUE TITLE
Raspberrypi onboard wifi doesn't work (4.12-y)

### ISSUE THREAD

**Issue by yfang1644** [raspberrypi/linux#2179] opened 2017-08-28 05:16 UTC
I'm compiling kernel 4.12.9 (arm64). The modules  brcmfmac and  brcmutil are installed,
but the wifi doesn't work.  kernel-4.11-y works find.

**Comment by UMRnInside** [comment] 2017-08-28 06:40
See issue #2124,it **MIGHT** be helpful.

**Comment by yfang1644** [comment] 2017-08-28 09:13
It's really helpful. Many thanks!

**Comment by popcornmix** [comment] 2017-08-30 11:51
Closing this as duplicate of #2124

**Closed as completed by popcornmix** 2017-08-30 11:51 UTC
