### ISSUE TITLE
Pi4 Sata Drive via USB kills Wifi

### ISSUE THREAD

**Issue by DavidAHMorton** [raspberrypi/linux#5264] opened 2022-12-06 06:10 UTC
### Describe the bug

This is the text of an email to the Pi Foundation, they insist I put it here.
"I have some feedback for you in the form of an observation: a Pi 4 does not have WiFi if I boot from an external USB drive plugged into USB3  port, but a USB 2 port is OK.
My gear: 4 x Pi4 (1, 2, 4 & 8GB), a 2.5 inch Hitachi 160 GB HDD, a  SanDisk Blue 500 GB SSD and a SimpleCom USB to Sata adaptor.  My test  "sudo apt update" from a command line, once booted. This is consistent across all 4 Pis, on either drive: No WiFi on USB 3,  OK on USB 2.
If Simplecom is not known to you (it pops up saying  "JMicron Generic" (I think I recall correctly). Thought you might wish to know my observations.  Others can decide if it  is a bug or not, and why it happens.  I'd like a reply to know when  this is fixed, although I realize it may be too much to ask".
I shall add that a Pi3B+ is also fine, but it doesn't have USB3

### Steps to reproduce the behaviour

Just try booting a Pi 4 off a SATA drive.

### Device (s)

Raspberry Pi 4 Mod. B

### System

Buster & Bullseye, both fully updated on every attempt.  I avoid all other tech detail that don't pertain to making Mathematica run.

**Comment by P33M** [comment] 2022-12-06 07:02
This interference issue is common and as old as USB3 - see this Intel whitepaper for suggested mitigations: https://usb.org/sites/default/files/327216.pdf
Closing as not a bug.

**Closed as not planned by P33M** 2022-12-06 07:02 UTC
