### ISSUE TITLE
add USB touchscreen support to kernel

### ISSUE THREAD

**Issue by AloisKlingler** [raspberrypi/linux#844] opened 2015-02-20 19:40 UTC
I think it would be a big improvement, as many usb touchpanes use the egalaxy driver.

Device Drivers->Input Device Support->TouchScreens

please add them to kernel as loadable modules. 

thanks!

**Comment by popcornmix** [comment] 2015-02-21 13:19
Duplicate of: https://github.com/raspberrypi/linux/issues/718

**Closed as completed by popcornmix** 2015-02-21 13:19 UTC
