### ISSUE TITLE
3.10.19 ALSA problems

### ISSUE THREAD

**Issue by stupid-boy** [raspberrypi/linux#442] opened 2013-11-20 12:05 UTC
uname -a
Linux raspberrypi 3.10.19+ #600 PREEMPT Sat Nov 16 20:34:43 GMT 2013 armv6l GNU/Linux

usb audio card: Audio Advantage MicroII
( http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=066624c6a1733a72a67f1d06d35a2153e7d9082b does not help! )

/etc/asound.conf:

```
pcm.!default
{
   type plug
   slave {
       pcm "Myiec958"
   }
}

ctl.!default
{
  type hw;
  card 1;
  device 0;
}

pcm.!Myiec958 {
        type hw
        card 1
        device 0
}
```

```
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=Device
    USB Sound Device, USB Audio
    Default Audio Device
front:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    Front speakers
surround40:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=Device,DEV=0
    USB Sound Device, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
```

on boot i get in dmesg:

```
[   12.051379] usb_audio: Warning! Unlikely big volume range (=9472), cval->res is probably wrong.
[   12.121720] usb_audio: [13] FU [PCM Playback Volume] ch = 2, val = -9473/-1/1<6>[   12.251980] usbcore: registered new interface driver snd-usb-audio
```

amixer fail with:

```
"amixer: Mixer attach default error: Invalid argument"
```

"speaker-test -t sine  -Dplug:sysdefault -c 2" ( play on HDMI ) generates in dmesg:

```
[  335.104885] bcm2835_audio_close:744 bcm2835_audio_close: failed on waiting for event (status=0)
[  335.104998] vc_vchi_audio_deinit:331 vc_vchi_audio_deinit: failed to close VCHI service connection (status=1)
```

"speaker-test -t sine  -Dplug:Myiec958 -s 1" generates 169 of these in dmesg:

```
delay: estimated 0, actual 144
```

"aplay whitenoise.wav" again a lot of these in dmesg:

```
 delay: estimated 0, actual 144
```

( wget http://www.stuffnewspaper.com/sounds/MISC/whitenoise.wav )

a lot of audio drops in spdif. even sometimes receiver turn off it PCM light. spikes on HDMI when channels are changed by speaker-test.
with previous official 3.6 version boot warning was not here, amixer opens without problems, drops in spdif was occasional ( not with speaker-test and didn't tested aplay whitenoise.wav , but still same message was logged by other software too, with rare occurrences and much less drops ), changes of channels on HDMI without spikes.

**Comment by P33M** [comment] 2014-05-02 11:02
Please retest with latest rpi-update firmware.

This is a duplicate of audio issues already reported (and fixed): if you continue to experience issues with your particular device then I will re-open the issue.

**Closed as completed by P33M** 2014-05-02 11:02 UTC
