### ISSUE TITLE
ath9k_htc doesn't work with aarch64 kernel

### ISSUE THREAD

**Issue by Zenitur** [raspberrypi/linux#2303] opened 2017-12-11 19:29 UTC
I just built 64-bit Linux kernel for Raspbian Linux using this manual: http://www.tal.org/tutorials/raspberry-pi3-build-64-bit-kernel

I have hostapd in my runlevels, it starts AP on ath9k_htc, it's working one minute, then stop to work without any errors.

[dmesg on 64-bit](https://pastebin.com/QcieV54V), [dmesg on 32-bit](https://pastebin.com/vL0nGBKa)

**Comment by pelwell** [comment] 2017-12-11 20:05
If you get the same behaviour on a 32-bit kernel then you have a slim chance of some support, but using host AP on a random WiFi device you are almost certainly better off asking in the Forums.

**Comment by lategoodbye** [comment] 2017-12-22 12:02
@Zenitur In case this issue is reproducible with a least Linux 4.14 it should be reported to linux-wireless mailing list and fixed upstream.

https://wireless.wiki.kernel.org/en/users/drivers/ath9k_htc

**Comment by JamesH65** [comment] 2018-04-20 15:18
@Zenitur Anything to report, I'm inclined to close this as a upstream issue.

**Comment by JamesH65** [comment] 2018-06-27 11:22
Closing due to lack of activity. Please request to be reopened if you feel this issue is still relevant.

**Closed as completed by JamesH65** 2018-06-27 11:22 UTC
Labels: Waiting for external input
