### ISSUE TITLE
add MPTCP (Multipath TCP)-support to kernel

### ISSUE THREAD

**Issue by gstammw** [raspberrypi/linux#713] opened 2014-10-23 13:30 UTC
Hello community,

Multipath TCP ("MPTCP") enables seamless handover between different network connections like a wlan and 3G as well as bandwidth aggregation if the remote-site is also mptcp enabled.
See http://multipath-tcp.org/ for further details.

I hope that the communiity aggrees that this is a very interesting feature that should be added to the raspbian default-kernel.
The sourcecode is available at http://multipath-tcp.org/pmwiki.php?n=Main.Release89 and they have already ported mptcp to Rasppbery PI at https://github.com/multipath-tcp/mptcp-rpi.

Kind regards

I have cross-compiled it myself on Ubuntu 14.04.1LTS following https://gist.github.com/davasiloaei/7301598:
## Prerequisites for compiling

$ sudo apt-get install gcc-arm-linux-gnueabi make ncurses-dev
## CHECKOUT

$ mkdir rpi_mptcp_kernel
$ cd rpi_mptpc_kernel
$ git clone --depth 1 git://github.com/raspberrypi/linux.git
Merge MPTCP kernel source and Raspberry PI 3.12.y into rpi_mptcp:
$ git init
$ git remote add mptcp https://github.com/multipath-tcp/mptcp.git
$ git fetch mptcp --depth 1
$ cd linux/.git
$ git branch -a
$ cd ..
$ git checkout -b rpi_mptcp origin/rpi-3.12.y
$ cd ..
$ git merge -X theirs mptcp/mptcp_v0.89
## COMPILE

Clean:
$ make mrproper
Get default rpi configuration:
$ make ARCH=arm bcmrpi_defconfig
Open the configuration gui:
$ make ARCH=arm nconfig
Under Networking Support ---> Networking options, enable 'The IPv6 protocol'. 2 more options should show up under IPv6 Protocol (MPTCP protocol and MPTCP: advanced path-manager control). Enable both, then exit and save.
Configure the cross compiler prefix:
$ export CCPREFIX=arm-linux-gnueabi-
Cross compile:
$ make ARCH=arm CROSS_COMPILE=${CCPREFIX}

**Comment by popcornmix** [comment] 2014-10-23 15:44
Has the kernel code for this been upstreamed?
We're very unlikely to include non-upstreamed code in the kernel without a compelling reason.

**Comment by gstammw** [comment] 2014-10-23 15:51
No the master kernel code has not yet been amended by the MPTCP-code.

It still makes sense as Multipath-TCP is a very interesting protocol that allows seamless handover between networks e.g. wifi to 3G/mobile as well as to combine the speed of two links.
I guess a lot of raspberryPIs are being used for homecenters and the second most use might be as a network server. In that case mptcp would be an interesting thing.

Let's stay ahead of the crows and adtop mptcp as the first ones :-)

**Comment by popcornmix** [comment] 2014-10-23 15:56
Sorry, not happening with official kernel. There's a high chance of regressions, a maintenance headache when moving to newer kernels, and a very small set of users who will benefit.

Feel free to create a fork of the pi kernel tree and include the MPTCP patches. You can publish custom kernels for interested users.

**Closed as completed by popcornmix** 2014-10-23 15:56 UTC

**Comment by opensourcegeek** [comment] 2016-10-18 11:01
@gstammw Did you get to fork this repo and apply mptcp patches?

**Comment by oionos75** [comment] 2017-02-15 15:56
In order to avoid the risks @popcornmix  mentions would n't it be more simple to port in Raspbian the Debian package mptcp  on https://dl.bintray.com/cpaasch/deb for jessie  ?

I'd like to test mptcp in a raspberry pi mesh network, I agree with @popcornmix that kernel recompilation is not the answer.  But porting a debian package?

**Comment by dur3x** [comment] 2017-04-17 12:40
@popcornmix  I'm trying to port mptcp on my raspberry pi (1 B) but it's currently difficult.
I tried to merge rpi-4.1.y with mptcp 0.91 but it didn't work :-(
I followed the procedure (with some changes) from @gstammw but I got that:
```
# make ARCH=arm bcmrpi_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
***
*** Can't find default configuration "arch/arm/configs/bcmrpi_defconfig"!
***
scripts/kconfig/Makefile:105: recipe for target 'bcmrpi_defconfig' failed
make[1]: *** [bcmrpi_defconfig] Error 1
Makefile:541: recipe for target 'bcmrpi_defconfig' failed
make: *** [bcmrpi_defconfig] Error 2
```
Can you help me ? 
Thanks :)

**Comment by popcornmix** [comment] 2017-04-18 13:58
You don't have the file ``arch/arm/configs/bcmrpi_defconfig``
That should come from:
https://github.com/raspberrypi/linux/blob/rpi-4.9.y/arch/arm/configs/bcmrpi_defconfig

Make sure you start with the raspberrypi/linux kernel tree and then apply whatever mptcp patches.

But you are right - porting out of tree drivers to new kernel versions is hard - hence the comment "maintenance headache".

Really you should be encouraging the author the out-of-tree driver to submit his driver upstream. Once it is accepted upstream use of it becomes much easier.

**Comment by dur3x** [comment] 2017-04-18 20:50
Indeed it's a little bit complicated :-) 
Currently I have a rpi with mptcp 0.88/0.89 & kernel 3.16 but I got some problems to create new subflows. The idea was just to try a more recent version of kernel+mptcp to see if the problem are solved (or not). 
Perhaps the problem is only something wrong on my initial setup.
Btw, thanks for your answer
ps: if you have, by chance, a rpi (1) with mptcp I'm very interested to know your setup and see if this one is really working as expected, otherwise no problem :)

**Comment by patcbuilds** [comment] 2017-09-08 21:45
Not sure if there's much movement on this, but I did find someone who has v0.92 working with a 4.4.50 kernel on a Pi 3. I'm attempting to replicate the directions to see if I can script this somehow with newer versions of the kernel.

http://mptcp.zugaina.com
https://github.com/Ysurac/raspberry_kernel_mptcp

**Comment by c1ngular** [comment] 2018-06-05 03:53
Anyone updates on this ?  This is intriguing

**Comment by c1ngular** [comment] 2018-06-07 02:10
at least a tutorial how to install mptcp on Pi 3 if it is not gonna be added to kernel by default ?

**Comment by pelwell** [comment] 2018-06-07 08:34
Raspberry Pi won't be writing such a guide, but we'll host it on the [wiki](https://github.com/raspberrypi/linux/wiki) if somebody wants to contribute one.
