### ISSUE TITLE
I2S channel swap on RPi3 on 32-bit Full-Duplex

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2473] opened 2018-03-27 17:56 UTC
I'm seeing channels been swap on 4.9.
Do we need this patch : https://github.com/raspberrypi/linux/commit/df7ab44a6e49c2810222b3d830f7ae2156fbc721 
on 4.9 ?

**Comment by ghost** [comment] 2018-03-27 18:00
My issue is : 
[  131.716996] bcm2835-i2s 3f203000.i2s: I2S SYNC error!
[  181.607101] bcm2835-dma 3f007000.dma: DMA transfer could not be terminated

But after applied this patch and run through the night no more issues.

**Comment by HiassofT** [comment] 2018-03-28 09:04
Please post more detailled info:

- Which RPi are you using?
- Which kernel and fiirmware versions are you using? Have you checked if it also happens on kernel 4.14?
- Which audio card are you using? Is it configured as I2S clock master? What parameters (format, samplerate) are used?
- Which software are you running?
- How often do you see channel swaps?

The commit you linked to was specific to left/right channel swaps when using 16bit format on RPi3 - other RPis and 24/32 bit formats were fine - see discussion in #1417

**Comment by ghost** [comment] 2018-03-28 11:42
Issue : 
Playback and record at the same time using:
play -f S32_LE -c2 -r48000 music.wav
arecord  -f S32_LE -c2 -r48000 result.wav

The AIF1 from the Codec is set as a loopback: RPI I2S -> CODEC AIF3 -> RPI I2S. 
Codec is Frame clock and Bit clock master.

board : Raspberry Pi 3 
sound card : https://www.cirrus.com/applications/smart-home/digital-assistant/

This issue can be reproduced 50% of times, with 4.9.

root@raspberrypi:~#  /opt/vc/bin/vcgencmd version
Mar 23 2018 16:31:10 
Copyright (c) 2012 Broadcom
version d92349b3d22c277e44d508a2aae6af2b1e5bb224 (clean) (release)

**Comment by HiassofT** [comment] 2018-03-28 15:08
I did some tests here with the Cirrus Logic Audio Card (WM5102) but couldn't reproduce the issue.

RPi I2S is connected to AIF1 and I setup AIF1 to loop back the input directly to the output
```
amixer -q -c RPiCirrus cset name=AIF1TX1 Input 1 AIF1RX1
amixer -q -c RPiCirrus cset name=AIF1TX2 Input 1 AIF1RX2
```
In addition to that I routed the input to SPDIF (WM8804 on AIF2) so I could check with the VU meter on my DAC which channel was active. I also hooked up a scope to the I2S lines to check to verify which channel data is driven.

Then I played a 32bit 48kHz WAV with a 440Hz sine only on the left channel
```
aplay -v audiotest/440hz-left-48000-32bit.wav
```
and recorded in another terminal
```
arecord -f S32_LE -c 2 -r 48000 recXX.wav
```
SPDIF monitor output, I2S signals on scope and the recorded wav were all fine.

Could you try to replicate that test? I.e. loop back on AIF3 instead of AIF1 to rule out issues with the codec? 

Checking with a scope is also a good idea, then you know if the I2S output from the RPi is fine and the looped back output from the codec is fine. If the I2S signals are all OK but the recorded WAV is not it most be in the receiving side.

Do you have a link to the machine driver code? What parameters are you using on the I2S connection (i.e. I2S, justified or DSP mode, TDM setup / bclk ratio)?

**Comment by ghost** [comment] 2018-04-03 10:25
Could you try to replicate that test? 
Sorry, my board is different from your. I don't think I can do the same test as yours.

Using logic analyser the channels are not swapped.

**Comment by ghost** [comment] 2018-04-03 10:26
My dmesg: 

[ 4015.578542] arizona spi0.1: Mixer dropped sample
[ 4015.579337] bcm2835-i2s 3f203000.i2s: I2S SYNC error!
[ 4015.579866] bcm2835-i2s 3f203000.i2s: I2S SYNC error!
[ 4016.631039] arizona spi0.1: ASRC underclocked
[ 4067.681675] bcm2835-dma 3f007000.dma: DMA transfer could not be terminated

**Comment by ghost** [comment] 2018-04-03 10:26
My Kernel: 
Linux version 4.14.31-v7+ (tanureal@tanurealDebian) (gcc version 4.9.2 20140904 (prerelease) (crosstool-NG linaro-1.13.1-4.9-2014.09 - Linaro GCC 4.9-2014.09)) #1 SMP Mon Apr 2 17:02:57 BST 2018

**Comment by ghost** [comment] 2018-04-03 10:27
root@raspberrypi:~# /opt/vc/bin/vcgencmd version
Mar 23 2018 16:31:10 
Copyright (c) 2012 Broadcom
version d92349b3d22c277e44d508a2aae6af2b1e5bb224 (clean) (release)

**Comment by ghost** [comment] 2018-04-03 10:28
My test Script: 
```
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[00;32m'
NC='\033[0m' # No Color

_name=$(date +%H%M%S)
echo "Test" $_name

_check_loopback ()
{
	tinymix set "AIF1TX1 Input 1" AIF1RX1
	tinymix set "AIF1TX2 Input 1" AIF1RX2

	sox -c 2 -r 48000 -b 32 --no-dither -n -t alsa hw:0 synth 12.0 sine 697 sine 1209 &>/dev/null &
	sleep 1
	arecord -d 10 -f S32_LE -c2 -r48000 "$_name"_record.wav &> /dev/null &

	wait
	sync

	sox "$_name"_record.wav "$_name"_left.wav remix 1 &> /dev/null
	sox "$_name"_record.wav "$_name"_right.wav remix 2 &> /dev/null
	_Lfreq=$(sox -c 1 -r 48000 -b 32 --no-dither "$_name"_left.wav -n  stat 2>&1 | grep 'frequency:')
	_Rfreq=$(sox -c 1 -r 48000 -b 32 --no-dither "$_name"_right.wav -n  stat 2>&1 | grep 'frequency:')

	if [ $? -ne 0 ]; then
		printf "Failed to capture ($?)\n"
	fi

	if [ -z "$_Lfreq" ]; then
		printf "Failed to measure left frequencies\n"
	fi
	if [ -z "$_Lfreq" ]; then
		printf "Failed to measure right frequencies\n"
	fi

	# Get just the numbers
	_Lfreq="$(echo "$_Lfreq" | cut -d ':' -f 2)"
	_Rfreq="$(echo "$_Rfreq" | cut -d ':' -f 2)"

	# Echoing $_freq without "" strips spaces
	_fl="$(echo $_Lfreq | cut -d ' ' -f 1)"
	_fr="$(echo $_Rfreq | cut -d ' ' -f 2)"

	if ! [[ $_fl =~ ^[0-9]+$ ]]; then
		printf "Unexpected data ($_fl) from sox stat\n"
	fi

	if ! [[ $_fr =~ ^[0-9]+$ ]]; then
		printf "Unexpected data ($_fr) from sox stat\n"
	fi

	# Frequency measurement isn't precise so must allow a range
	if [ $_fl -lt 687 ] || [ $_fl -gt 707 ]; then
		printf "${RED}FAIL${NC} Expected 687-707 got $_fl\n"
	else
		printf "${GREEN}PASS${NC} Left channel frequency ok ($_fl)\n"
	fi

	if [ $_fr -lt 1199 ] || [ $_fr -gt 1219 ]; then
		printf "${RED}FAIL${NC} Expected 1199-1219 got $_fr\n"
	else
		printf "${GREEN}PASS${NC} Right channel frequency ok ($_fr)\n"
	fi

	rm -rf "$_name"_record.wav "$_name"_right.wav "$_name"_left.wav

	tinymix set "AIF1TX1 Input 1" None
	tinymix set "AIF1TX2 Input 1" None
	printf "#######################################\n"
}

length=$1
for ((i=0; i<length; i++)); do
	_check_loopback
done
```

**Comment by HiassofT** [comment] 2018-04-04 13:49
I tested with your script but couldn't reproduce the issue here with the official rpi-update kernel and the Cirrus Logic audio card on RPi3. I let it check 50 recordings but got a PASS in all cases.

I noticed 2 suspicious things in your dmesg snippet though:

"I2S SYNC error!" is output 2 times in quick succession, when bcm2835-i2s is clock slave one line is usual (probably because the external clock hadn't been started yet).

"DMA transfer could not be terminated" is very odd. I've only seen that when bcm2835-i2s is clock slave no external clock had been applied.

Are the clocks on the cs47l24 maybe enabled too late and disabled too early?

**Comment by ghost** [comment] 2018-04-04 14:34
I changed to use 0 on left chanel and 1209 on right channel. 
I continue to see the channel swap.
![bus_analysis](https://user-images.githubusercontent.com/79954/38314202-9848ce3e-381d-11e8-83be-75d60255b6a9.PNG)

**Comment by ghost** [comment] 2018-04-04 14:35
Changing to this test I get 100 success cases:
```
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[00;32m'
NC='\033[0m' # No Color

_check_loopback ()
{
	test_name=$1
	tinymix set "AIF3TX1 Input 1" AIF3RX1
	tinymix set "AIF3TX2 Input 1" AIF3RX2
	tinymix set "HPOUT1L Input 1" AIF3RX1
	tinymix set "HPOUT1R Input 1" AIF3RX2
	tinymix set "HPOUT1 Digital Switch" 1

	sox -c 2 -r 48000 -b 32 --no-dither -n -t alsa hw:0 synth 12.0 sine 0 sine 1209 2> /dev/null &
	sox_pid=$!
	sleep 1
	arecord -d 10 -f S32_LE -c2 -r48000 "$test_name"_record.wav 2> /dev/null &
	arecord_pid=$!
	
	wait $sox_pid
	wait $arecord_pid
	sync

	sox "$test_name"_record.wav "$test_name"_left.wav remix 1 &> /dev/null
	sox "$test_name"_record.wav "$test_name"_right.wav remix 2 &> /dev/null
	_Lfreq=$(sox -c 1 -r 48000 -b 32 --no-dither "$test_name"_left.wav -n  stat 2>&1 | grep 'frequency:')
	_Rfreq=$(sox -c 1 -r 48000 -b 32 --no-dither "$test_name"_right.wav -n  stat 2>&1 | grep 'frequency:')

	if [ $? -ne 0 ]; then
		printf "Failed to capture ($?)\n"
	fi

	if [ -z "$_Lfreq" ]; then
		printf "Failed to measure left frequencies\n"
	fi
	if [ -z "$_Lfreq" ]; then
		printf "Failed to measure right frequencies\n"
	fi

	# Get just the numbers
	_Lfreq="$(echo "$_Lfreq" | cut -d ':' -f 2)"
	_Rfreq="$(echo "$_Rfreq" | cut -d ':' -f 2)"

	# Echoing $_freq without "" strips spaces
	_fl="$(echo $_Lfreq | cut -d ' ' -f 1)"
	_fr="$(echo $_Rfreq | cut -d ' ' -f 2)"

	if ! [[ $_fl =~ ^[0-9]+$ ]]; then
		printf "Unexpected data ($_fl) from sox stat\n"
	fi

	if ! [[ $_fr =~ ^[0-9]+$ ]]; then
		printf "Unexpected data ($_fr) from sox stat\n"
	fi

	# Frequency measurement isn't precise so must allow a range
	if [ $_fl -lt 0 ] || [ $_fl -gt 7 ]; then
		printf "${RED}FAIL${NC} Expected 0-7 got $_fl\n"
	else
		printf "${GREEN}PASS${NC} Left channel frequency ok ($_fl)\n"
	fi

	if [ $_fr -lt 1199 ] || [ $_fr -gt 1219 ]; then
		printf "${RED}FAIL${NC} Expected 1199-1219 got $_fr\n"
	else
		printf "${GREEN}PASS${NC} Right channel frequency ok ($_fr)\n"
	fi

	tinymix set "AIF3TX1 Input 1" None
	tinymix set "AIF3TX2 Input 1" None
	tinymix set "HPOUT1 Digital Switch" 0
	tinymix set "HPOUT1L Input 1" None
	tinymix set "HPOUT1R Input 1" None
	printf "#######################################\n"
}

length=$1
for ((i=0; i<length; i++)); do
	_name=$(date +%H%M%S)
	echo "Test" $_name
	_check_loopback $_name
done
```

**Comment by ghost** [comment] 2018-04-04 14:37
The change on the previous test was add another route for playback, so playback and properly start before the record. 
So it seems that DMA or I2S on rpi has a problem that can't handle when the playback starts without anyone consuming it.

**Comment by HiassofT** [comment] 2018-04-04 15:21
Ah, now everything's clear.

The problem is that the codec will stay in DAPM bias level off and doesn't drive clocks until both audio output and audio input have started.

That's because there is no DAPM route through the codec to any external input/output.

You can easily check that with running just speaker-test/sox/aplay or just arecord - I2S clocks aren't driven and the codec bias_level in /sys/kernel/debug/asoc/... reports "Off". And a few seconds later the programs will error out with input/output errors.

There's an easy solution to that, add dummy input and output widgets to the machine driver and routes from the codec's inputs/output to these. Then the codec will go to bias level "on" and start clocks even if there are no other routes to external input/output.

See eg my implementation in the rpi-cirrus driver:
https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/soc/bcm/rpi-cirrus.c#L381-L382
```
	SND_SOC_DAPM_INPUT("Dummy Input"),
	SND_SOC_DAPM_OUTPUT("Dummy Output"),
```
https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/soc/bcm/rpi-cirrus.c#L412-L415
```
	{ "Dummy Output", NULL, "AIF1RX1" },
	{ "Dummy Output", NULL, "AIF1RX2" },
	{ "AIF1TX1", NULL, "Dummy Input" },
	{ "AIF1TX2", NULL, "Dummy Input" },
```

**Comment by ghost** [comment] 2018-04-04 15:27
But why Rpi DMA/I2S drivers can't wait until the clocks are there to start to playback and record. 
Still feels like Rpi is doing something wrong because I can see the swapped channels.

**Comment by HiassofT** [comment] 2018-04-04 16:00
The problem seems to be that clearing the fifos seems to fail if there's no clock present. So bcm2835-i2s will start output with fifos in unclear state - which matches my observation and your captures, data output by bcm2835-i2s has the channels swapped.

There are 2 calls to clear fifos, one from hw_params() that clears both input and output fifos, which usually fails in slave mode because external clocks aren't started yet, but then the second call from prepare() which only clears the fifo for the current stream succeeds - if the external clocks have been started.

So this is why you are getting two "I2S SYNC error"s, the first one is harmless but the second one has to be taken serious.

**Comment by ghost** [comment] 2018-04-04 16:23
can you show me which line in your code clears the fifo ?

**Comment by ghost** [comment] 2018-04-04 16:38
Oh, you mean on the bcm2835-i2s.c ?

**Comment by HiassofT** [comment] 2018-04-04 16:41
yes, fifo clear happens in the I2S driver. This is nothing we have to care about - other than making sure the clocks are enabled when the driver expects them to be :)

**Comment by ghost** [comment] 2018-04-28 17:09
Hardware Bug in Raspberry Pi, impossible to fix by software

**Comment by JamesH65** [comment] 2018-06-29 13:40
Since the OP has deleted their github account, should this issue be closed?

@HiassofT Do you agree this is a HW bug and insurmountable, or is there actually something that can and should be done?

**Comment by HiassofT** [comment] 2018-06-29 14:01
I'm more inclined to see this as a usage issue than a hardware bug - not providing clocks and expecting things to work fine is a bit odd - but at the end of the day it doesn't make a difference, there's nothing we can do about it. So just close the issue.

**Closed as completed** 2018-06-29 14:06 UTC
Labels: Waiting for external input

**Comment by lucastanure** [comment] 2019-07-04 13:32
@HiassofT There is a way provide this clock in slave mode ?

**Comment by lucastanure** [comment] 2019-07-04 13:35
Looking into Raspberry 4 I2S driver, it seems that RPI4 will use the same driver.
So the new board will have the same issue, where in slave mode it can't clear the fifo because it can't receive the clock.
There is a way to provide this clock ?
What I don't understand is that Frame and Bit clock are there, but the BCM chip doesn't get the clock to clear the FIFO, so I'm missing any hardware change or any software change ?
