### ISSUE TITLE
Audio quality from aux is poor

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/linux#4357] opened 2021-05-22 16:03 UTC
It sounds like the speaker is put inside 
a carton box or something. 

If I play same song to same speakers from iPhone via Bluetooth the quality is much better. 

When it comes out aux is quite poor no matter which speakers/ headphones I use. 

Thanks

**Comment by popcornmix** [comment] 2021-05-22 16:27
What do you mean by aux? The 3.5mm headphone jack?

**Comment by mgrouch** [comment] 2021-05-22 18:36
Yes

**Comment by popcornmix** [comment] 2021-05-22 18:47
The audio output is basic, using filtered output from PWM, rather than a dedicated DAC.
That may just be how it is. HDMI will give better quality, as will an I2S audio HAT, USB dongle or bluetooth.

**Comment by P33M** [comment] 2021-05-25 18:11
The "aux" (3.5mm jack) audio uses a driver circuit that has a shoestring budget. It does not have good bass reproduction when driving low-impedance loads - I recommend a minimum of 10kohms sink impedance for an acceptable frequency response. 

Absent any further information, I'm closing this as the design works as intended.

**Closed as completed by P33M** 2021-05-25 18:11 UTC
