### ISSUE TITLE
usb wlan in bridge error

### ISSUE THREAD

**Issue by tiagoasousa** [raspberrypi/linux#638] opened 2014-07-18 11:44 UTC
I have the following issue:

rpi with 1 ralink rt5370 connected, bridged with eth0, nothing else connected to usb or gpio.
usb psu of 1 amp (http://pt.farnell.com/raspberry-pi-psu/rpi-psu-eu-mk1/power-supply-raspberry-5v-1a-euro/dp/2254794)
hostapd is being used as Access Point.
no overclock
as soon as i connect the wlan dongle, the rpi starts to crash.

on dmesg the only info that I can find is:

ERROR::dwc_otg_hcd_urb_enqueue:505: Not connected

I tried with 2 rpis (modelb/512) and 2 power supplies.

I don´t have hardware to measure, but i don´t think that 1 wlan dongle needs much power...

I think it should be some bug, but if anyone has any idea where to get more debug info i would apreciate it.

**Comment by popcornmix** [comment] 2014-07-18 13:33
It is almost certainly a voltage drop caused by an insufficient power supply. You need to measure to voltage on the board to confirm this:
http://elinux.org/R-Pi_Troubleshooting#Troubleshooting_power_problems

It won't be possible to fix this in software.

**Comment by PeterPablo** [comment] 2014-07-18 13:58
You might try to insert an actively powered USB hub between your Raspberry PI and the wifi dongle. This way you can quite easily rule out problems with the power supply.

**Comment by alevchuk** [comment] 2015-02-08 05:09
I'm (on B+) getting "dwc_otg_hcd_urb_enqueue:505: Not connected" as soon as I try to use the camera module.

(http://picamera.readthedocs.org/en/release-1.9/recipes1.html) camera.start_preview()

An other times when I try to run camera, the kernel crashes with kernel panic (but I can save the exact error messages).

I have kernel 3.18.6+ #1 PREEMPT with latest firmware.

**Comment by popcornmix** [comment] 2015-02-09 16:23
@alevchuk 
Does PWR led flicker or multi-coloured square appear in top-right corner?

**Comment by Ruffio** [comment] 2016-08-10 14:16
@alevchuk anything? Have you tried with latest firmware?

**Comment by P33M** [comment] 2017-05-04 15:15
Closing USB issues as OP has not updated the thread. Further comments by the OP stating that the issue is still present on latest rpi-update kernel will lead to a review.

**Closed as completed by P33M** 2017-05-04 15:15 UTC
