### ISSUE TITLE
Git Clone Issue

### ISSUE THREAD

**Issue by avnho** [raspberrypi/linux#71] opened 2012-08-01 01:14 UTC
I'm facing the following issue while trying to clone the repo.
## 1st Run:

root@raspberrypi:/usr/src# git clone git://github.com/raspberrypi/linux.git kernel
Cloning into 'kernel'...
remote: Counting objects: 2275352, done.
remote: Compressing objects: 100% (354872/354872), done.
remote: Total 2275352 (delta 1901628), reused 2268222 (delta 1898662)
Receiving objects: 100% (2275352/2275352), 465.43 MiB | 358 KiB/s, done.
git: builtin/index-pack.c:600: find_unresolved_deltas: Assertion `child->real_type == OBJ_OFS_DELTA' failed.
error: index-pack died of signal 6
fatal: index-pack failed
## 2nd Run:

root@raspberrypi:/usr/src# git clone git://github.com/raspberrypi/linux.git kernel
Cloning into 'kernel'...
remote: Counting objects: 2275352, done.
remote: Compressing objects: 100% (354872/354872), done.
Receiving objects: 100% (2275352/2275352), 465.43 MiB | 250 KiB/s, done.
remote: Total 2275352 (delta 1901628), reused 2268222 (delta 1898662)
error: inflate: data stream error (invalid distance too far back)
fatal: serious inflate inconsistency
fatal: index-pack failed

Any Ideas on this guys?

**Comment by popcornmix** [comment] 2012-08-10 10:32
I've tested this:
$ git clone git://github.com/raspberrypi/linux.git kernel
Cloning into kernel...
remote: Counting objects: 2275403, done.
remote: Compressing objects: 100% (360120/360120), done.
remote: Total 2275403 (delta 1901479), reused 2264177 (delta 1893465)
Receiving objects: 100% (2275403/2275403), 464.97 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (1901479/1901479), done.
$ ls kernel/
arch/    CREDITS         drivers/   include/  Kbuild   lib/         mm/     REPORTING-BUGS  security/  usr/
block/   crypto/         firmware/  init/     Kconfig  MAINTAINERS  net/    samples/        sound/     virt/
COPYING  Documentation/  fs/        ipc/      kernel/  Makefile     README  scripts/        tools/

Pretty sure the problem is at your end (a lot of people clone this repo). Reopen if you have more evidence there is a problem here.

**Closed as completed by popcornmix** 2012-08-10 10:32 UTC
