### ISSUE TITLE
rpi-4.4.y: ethernet hw csum failures when receiving ipv6 multicast traffic

### ISSUE THREAD

**Issue by Noltari** [raspberrypi/linux#1259] opened 2016-01-16 18:17 UTC
When adding support for 4.4 on OpenWrt I get the following warnings whenever the RPi receives IPv6 multicast traffic:
https://gist.github.com/Noltari/5b1cfdecce5ed4bc08fd
https://github.com/openwrt-es/openwrt/commit/964b80d4c0f259ef392aa984d69d41559f19efbd
The linux-4.4 patches where extracted from 4.4.y branch on this repo. However, I must say it could still be something OpenWrt specific.

Manually removing lines 1181-1186 seems to fix it (-> disabling hardware checksums):
https://github.com/raspberrypi/linux/blob/rpi-4.1.y/drivers/net/usb/smsc95xx.c#L1181

Any ideas?

BTW, here's my repo: https://github.com/openwrt-es/openwrt/commits/brcm2708-next

**Comment by popcornmix** [comment] 2016-01-17 13:48
Do you get the same issue with raspbian and untouched rpi-4.4.y kernel?

**Comment by Noltari** [comment] 2016-01-18 06:07
I will test that as soon as I can and report my results.

**Comment by Noltari** [comment] 2016-01-22 20:25
Hi again,

I didn't have time to do any tests, but doing some research it appears that this problem started on linux-4.2 and has been there since that version.
However, it may have been unnoticed since a bridge between different interfaces is required to trigger the error. It doesn't happen on single network interfaces.

Some other reports of this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1266601
https://discourse.osmc.tv/t/hw-csum-failure/9990

**Comment by popcornmix** [comment] 2016-01-22 20:36
Let us know you find any patches to fix it...

**Comment by Noltari** [comment] 2016-01-22 20:42
It appears that it was already reported on https://github.com/raspberrypi/linux/issues/1083 but I didn't see it :/

**Comment by popcornmix** [comment] 2016-01-23 12:46
Okay, closing as duplicate of #1083
Please add any useful discoveries to that issue.

**Closed as completed by popcornmix** 2016-01-23 12:46 UTC
