### ISSUE TITLE
Pulseaudio stack smashing error when starting

### ISSUE THREAD

**Issue by farias-automac** [raspberrypi/linux#6331] opened 2024-08-29 18:53 UTC
### Describe the bug

Hello, I have an error when launching pulseaudio service. I'm building the SO image (32 bits), with the kernel v6.6 for a CM4. It's a fresh test system with just Alsa, Pulseaudio, Systemd and Dbus. This is the error message when pulseaudio start:

...
D: [pulseaudio] alsa-util.c: start_threshold : -1
D: [pulseaudio] alsa-util.c: stop_threshold : 1073741824
D: [pulseaudio] alsa-util.c: silence_threshold: 0
D: [pulseaudio] alsa-util.c: silence_size : 0
D: [pulseaudio] alsa-util.c: boundary : 1073741824
D: [pulseaudio] alsa-util.c: appl_ptr : 0
D: [pulseaudio] alsa-util.c: hw_ptr : 0
D: [alsa-sink-MAI PCM i2s-hifi-0] alsa-sink.c: Thread starting up
D: [alsa-sink-MAI PCM i2s-hifi-0] util.c: SCHED_RR|SCHED_RESET_ON_FORK worked.
I: [alsa-sink-MAI PCM i2s-hifi-0] util.c: Successfully enabled SCHED_RR scheduling for thread, with priority 5.
D: [pulseaudio] sink.c: alsa_output.platform-fef00700.hdmi.hdmi-stereo: state: INIT -> IDLE
I: [alsa-sink-MAI PCM i2s-hifi-0] alsa-sink.c: Starting playback.
*** stack smashing detected ***: terminated
Aborted (core dumped)
root@raspberrypi4:~# stack smashing detected

### Steps to reproduce the behaviour

launch pulseaudio with pulseaudio -vvv

### Device (s)

Raspberry Pi CM4

### System

Linux raspberrypi4 6.6.22-v7l #1 SMP Tue Mar 19 17:41:59 UTC 2024 armv7l GNU/Linux

**Comment by pelwell** [comment] 2024-08-29 19:46
Duplicate of https://github.com/agherzan/meta-raspberrypi/issues/1362, where they are already trying to help you. This isn't a kernel problem.

**Closed as completed by pelwell** 2024-08-29 19:46 UTC
