### ISSUE TITLE
Bluetooth rfcomm binding broken in current raspbian kernel 3.12.x

### ISSUE THREAD

**Issue by sshivaji** [raspberrypi/linux#683] opened 2014-09-06 17:12 UTC
For bluetooth, the following typically happens.
1. Scan for devices
2. Get device MAC address
3. Pair device
4. Bind device to an rfcomm (e.g. /dev/rfcomm0)
5. Connect to that device on startup.

Unfortunately, with the current raspbian kernel (3.12.x), steps 4-5 are broken. The error message "Transport endpoint not connected" is encountered. The idea of binding a device is that when pyserial (or a similar program) opens the device, only then a connection is made. This is sort of a late binding. Late binding unfortunately is broken in this kernel. Refer to https://bugzilla.redhat.com/show_bug.cgi?id=1060457

Downgrading the kernel to 3.10 works fine. Unfortunately, I dont know exactly which of the latest kernel versions addresses this problem. According to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1342570, kernel 3.14.15 is the answer, however, its possible that an earlier 3.14 kernel has the fix too.

l originally documented this issue in https://github.com/jromang/picochess/issues/24 for an open source project.

**Comment by popcornmix** [comment] 2014-09-08 20:31
If you can find the upstream commit that fixes this, we can try to include it in 3.12 kernel.
You could try building your own kernel from the rpi-3.16.y branch which hopefully doesn't have this issue.
We may move to the 3.14.y tree in the near future which may solve your issue.

**Comment by sshivaji** [comment] 2014-09-19 18:16
Thx, will try to find the upstream commit

**Comment by solshark** [comment] 2015-01-03 14:04
Any news on it?

**Comment by solshark** [comment] 2015-01-03 14:32
Acually, using branch **next** for firmware fixed the issue.

**Comment by popcornmix** [comment] 2015-01-04 12:17
We'll be moving to next kernel soon, so the advice would be to stick with that until we do.

**Comment by sshivaji** [comment] 2015-01-04 17:20
The next branch works for our bluetooth issues, thx for pointing this out! We can close this issue once we move to the next kernel.

**Comment by Ruffio** [comment] 2016-08-10 14:20
@sshivaji has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment] 2016-12-30 11:46
This issue should be closed due to inactivity. Last activity was on 4 Jan 2015, and I have pinged on 10 Aug 2016 without any response.

On 3 Jan 2015 is was confirmed, that using branch next for firmware fixed the issue, which mean that is is ficed in current firmware...

**Closed as completed** 2016-12-30 15:50 UTC

**Comment by sshivaji** [comment] 2016-12-30 16:15
Apologies as we have abandoned the Docker path for picochess on the raspberry pi. Thus, it would be some work to test that route again. Keeping the issue closed is fine. We will reopen if we try that route again.

**Comment by sshivaji** [comment] 2016-12-30 17:27
Whoops, I was commenting on the wrong issue, this is just Bluetooth and the raspberry pi kernel, which indeed works well now and thus the issue is correctly closed!
