### ISSUE TITLE
Display Link USB Support (MiMO S720, etc)

### ISSUE THREAD

**Issue by pssc** [raspberrypi/linux#893] opened 2015-03-17 10:35 UTC
Could we consider adding:-

CONFIG_FB_MODE_HELPERS=y
CONFIG_FB_UDL=m

**Comment by popcornmix** [comment] 2015-03-22 14:09
Duplicate of https://github.com/raspberrypi/firmware/issues/141
I think there are still some question marks about performance with this change.
Please continue discussion in the open issue.

**Closed as completed by popcornmix** 2015-03-22 14:09 UTC
