### ISSUE TITLE
alsa hangs/stutters about 0,5s when mmcqd/0 works

### ISSUE THREAD

**Issue by mrzk-pl** [raspberrypi/linux#55] opened 2012-07-16 10:00 UTC
Everytime when mmcqd/0 eating CPU (about 12% CPU) I have short sound stutters.

I've tested various options:
- the same problem was when I've played music on mpd / mpg123 / aplay / pulseaudio stream from LAN
- the same problem on internal and external card (via usbaudio.ko). When playing music on two cards, the hang was in the same time on both cards (when mmcqd worked)
- tested on low / high cpu usage/load, on various snd quality (44100, 22050Hz)

I have Kingston SDHC 8GB Class10 (SD10G2/8GB) and default .asoundrc

**Comment by popcornmix** [comment] 2012-07-16 12:11
We currently block in sdcard driver which could possibly cause underflows on audio if this is happening.

There is a patch that avoids it:
https://github.com/grigorig/rpi-linux/commit/547d57b633cc117cbe6199ee202e272de924b1bf

but it needs testing. Here is a kernel built with it:
https://dl.dropbox.com/u/3669512/temp/kernel.img

Please test and report. Note there is a small chance of sdcard instability, so it's worth backup up sdcard first.

**Comment by mrzk-pl** [comment] 2012-07-17 07:13
Hi, thank for response. I've applied patch but nothing changes, alsa hangs. 
But after them I put my old SanDisk SD Card into Raspberry where I created backup before, and issue disappeared! 
Something is wrong with SD10G2/8GB, that is marked as compatible in RPi_VerifiedPeripherals

**Comment by popcornmix** [comment] 2012-07-17 09:48
With the bad sdcard, any error messages (in dmesg log) appearing when the sound stutters?

**Comment by mrzk-pl** [comment] 2012-07-18 06:49
No, zero logs. Only higher cpu usage (mmcq/0) on bad card

**Comment by popcornmix** [comment] 2012-08-20 21:09
Likely to be an instance of this:
https://github.com/raspberrypi/linux/pull/72
We know what the problem is, but no solution yet.

**Comment by popcornmix** [comment] 2012-08-21 11:08
Closing as duplicate of #72

**Closed as completed by popcornmix** 2012-08-21 11:08 UTC
