### ISSUE TITLE
Raspberry Pi fails to boot with "software i2c" enabled

### ISSUE THREAD

**Issue by fatihyo** [raspberrypi/linux#3673] opened 2020-06-12 19:07 UTC
Raspberry Pi fails to boot with "software i2c" enabled.

I'm using a Raspberry Pi 3 with
latest  "sudo apt-get update && sudo apt-get upgrade"d Raspberry OS Buster Lite
which is using

> 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

When I add the below line into /boot/config.txt;
`# Uncomment some or all of these to enable the optional hardware interfaces`
`#dtparam=i2c_arm=on`
`dtoverlay=i2c-gpio,bus=3`
`#dtparam=i2s=on`
`#dtparam=spi=on`

Raspberry Pi fails to boot.
Other than above configuration change, the install has all vanilla settings.

On another raspberry pi using

> 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020

with exact same settings
Raspberry Pi boots and "software i2c" works properly. 

Since 
`dtoverlay=i2c-gpio,bus=3`
 is a legit configuration based on dts/overlays/README, which should start "software i2c"; I suspect there may have been a change in the firmware or kernel that's causing this behavior. 

I also found this thread on raspberrypi.org forums concerning this issue. 
https://www.raspberrypi.org/forums/viewtopic.php?t=275762

**Comment by pelwell** [comment] 2020-06-12 19:57
Duplicate of https://github.com/raspberrypi/firmware/issues/1381, https://github.com/raspberrypi/firmware/issues/1401, and https://www.raspberrypi.org/forums/viewtopic.php?t=275991. The fixed overlay is available from rpi-update.

**Closed as completed by pelwell** 2020-06-12 19:57 UTC
