### ISSUE TITLE
Linux will not start with boot delay more than 7 seconds

### ISSUE THREAD

**Issue by ak59** [raspberrypi/linux#416] opened 2013-11-04 07:30 UTC
It seems that Raspberry shut down the HDMI interface on start, after round about 5 seconds. The “regular” HDMI settings generated by Noobs, in combination with a boot delay of more than 7 seconds, causes the system to halt. In this case the screen is black. No error message is shown and I didn't found any message in log files.
It seems, that Linux can't detect the HDMI interface after this time period and stops. I only found one way to wake up Linux after a sleep period of more than 7 seconds: By overwriting settings with “hdmi_safe=1” and “hdmi_force_hotplug=1“ or alternative “hdmi_ignore_hotplug=1“

**Comment by popcornmix** [comment] 2013-11-18 19:25
Does this issue only affect NOOBS, or is it present with just a raspbian image?

**Comment by ak59** [comment] 2013-11-26 09:55
A boot delay will also halt a image based installation.

**Comment by popcornmix** [comment] 2013-11-26 13:17
Are you saying if you take a fresh raspbian image, and add the line:
boot_delay=8
to config.txt it will fail to boot?

**Comment by ak59** [comment] 2013-11-26 15:32
Yes. I have tested it with boot_delay_ms. I changed it to 8000 and the system will not start. I changed it back to 2000 no problems.

**Comment by githubkusi** [comment] 2014-10-07 21:34
I can confirm the issue, having `boot_delay=10` won't let raspian boot. The delay is the only change I have in config.txt. 
My situation _without boot delay_: If the RP and the amplifier get powered at the same moment, the HDMI output seems dead. When I reboot the RP (keeping the amplifier powered on), everything works fine.

Situation _with boot_delay=10_: PWR LED is on, no other led is on or blinking. On the amplifier, I now select the RP as input, the ACT LED blinks 1x and the RP boots, with functional ssh etc.. but no HDMI.

Situation _with boot_delay=3_: RP boots after 3sec (regardless of the input selector of the amplifier), everything works as expected, including HDMI

**Comment by Ruffio** [comment] 2016-08-10 10:55
@ak59 has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment] 2016-08-29 15:52
@ak59 has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment] 2016-12-30 11:35
This issue should be closed due to inactivity. Last activity was on 7 Oct 2014, and I have pinged on 10 and 29 Aug 2016 without any response...

**Comment by githubkusi** [comment] 2016-12-30 12:18
@Ruffio : did anything change in the software stack which could have resolved the issue? If not then probably the issue is still there. Unfortunately, I don't have the time right now to check again

**Comment by Ruffio** [comment] 2016-12-30 13:13
@githubkusi I don't know. The issue is three years old and alot happens in three years, that is why I'm asking if it is still an issue. I pinged four months ago without any response, so my initial conclusion is that it has been fixed or that nobody cares.

**Comment by popcornmix** [comment] 2016-12-30 15:48
I'll close for now. A lot has changed in two years.
Feel free to reopen if testing shows it is still an issue.

**Closed as completed by popcornmix** 2016-12-30 15:48 UTC

**Comment by LMQTLV** [comment] 2019-08-22 13:51
Hi,
I don't know if I am at the good place, but I have apparently the same problem : as soon as I add "rootdelay=x" in my cmdline.txt, my PI doesn't go to HDMI, only composite is active.
As soon as I suppress "rootdelay=", I get back HDMI.
Tried with different monitors and different cables : not better.
Tried with auto-shutdown deactivated in monitor : not better.
Even with a delay of 4 seconds, HDMI is down.

**Comment by popcornmix** [comment] 2019-08-22 13:54
Create a new issue. This issue is about bootdelay which is a config.txt setting interpreted by firmware before kernel starts.
Your issue a about a cmdline.txt option that is interpreted by the kernel, so your issue won't be related to this (closed) issue.

**Comment by LMQTLV** [comment] 2019-08-22 13:55
OK, sorry and thank you for the answer :)
