### ISSUE TITLE
unable to handle kernel paging request ... swapper not tainted 

### ISSUE THREAD

**Issue by japrogramer** [raspberrypi/linux#357] opened 2013-08-16 00:47 UTC
http://i.imgur.com/4swdnOp.jpg 
Over at irc someone else had the same problem, fix is to replace /boot/kernel.img with an older kernel image and install that older kernel wonce booted to get rid of issing modules error... haven't tried to install latest kernel since

**Comment by popcornmix** [comment] 2013-08-16 08:57
Need more info. What kernel/distro are you running? 
When did this start happening?

**Comment by ajs124** [comment] 2013-08-16 15:52
This might be a duplicate of #356. The error messages are pretty similar. @japrogramer, you are talking about the linux-raspberrypi-latest package (upgrade from 3.10.4 to 3.10.6) from archlinux arm and their irc, right?

**Comment by yann-morin-1998** [comment] 2013-08-16 17:50
I have the same issue building `bcmrpi_quick` defconfig on branch `rpi-3.10.y` since it has been rebased ontop `stable/linux-3.10.6`.

I've rebased the `rpi-3.10.y` branch ontop of each cset since `stable/linux-3.10.5`, and I've found that rebasing `rpi-3.10.y` ontop `b85796f ARM: move vector stubs` is the first to break. If that can help...

For now, I'm keeping a local `rpi-3.10.y` rebased ontop `stable/linux-3.10.5`.

Note: since `rpi-3.10.y` has since been rebased again, I no longer have the sha1 for the old `HEAD` that was broken. I'll retry now that `rpi-3.10.y` has been rebased ontop `stable/linux-3.10.7`, and will keep you posted on the results.

BTW, it would be nice if you would maintain the`rpi-3.10.y` branch stable (git-wise, not speaking of the code), by merging from upstream as you do for `rpi-3.6.y`. That would be nice to help bisect changes without a constantly-moving code-base. Cheers! ;-)

**Comment by yann-morin-1998** [comment] 2013-08-16 18:17
OK, this seems to be fixed by `623b25d ARM: Fix FIQ code on VIVT CPUs`. Sorry for the noise. Thanks! :-)

**Comment by japrogramer** [comment] 2013-08-16 19:15
I was using 3.10.6-1 arch arm , now that the code is rebased I might try the latest again

**Comment by yann-morin-1998** [comment] 2013-08-16 20:14
Yes, `rpi-3.10.y` was rebased less than 24h ago. Works like a charm here, now.

**Comment by P33M** [comment] 2014-05-05 13:10
This is fixed in 3.10.y and upwards.

**Closed as completed by P33M** 2014-05-05 13:10 UTC
