### ISSUE TITLE
Issue about hso driver interfaces (monitor 3G signal)

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#633] opened 2014-07-08 16:21 UTC
Hi,

(I apologize for my bad english ('m a french student) and apologize too if this issue is in the wrong place, didn't know where to post it)

I'm currently setting up my pi as a 3G hotspot. I've got an Option Icon 225 branded by "Orange" which is an HSxPA Modem.
It is recognized by raspbian out of box (since last Raspbian update) but there is something that went wrong. In /dev, the modem has 4 interfaces : 
/dev/ttyHS0 -> Seems to be "Control" interface, doesn't respond to AT command and seems to be inactive in minicom, (can't input anything) 
/dev/ttyHS1 -> Seems to be "Application" interface, doesn't respond to anything and seems to be inactive in minicom.
/dev/ttyHS2 -> Seems to be "Diagnostic" interface, doesn't respond to anything and seems to be inactive in minicom.
/dev/ttyHS3 -> It's is "Modem" interface, the only interface that respond to AT command, which is active in minicom, and the one pppd can use to make data-connection
BUT, when pppd is connected, /dev/ttyHS3 is locked and you can't input anything to serial and you can't get signal strenght infos and that's what I want to do ... 
I know it's possible to get signal infos or to input AT commands while pppd is connected because Orange's and Option's apps in Windows or Pharescape's old app on linux support that,
I think It's an issue in the hso driver, or is there anything I forgot ?
Thanks in advance,

Florian

**Comment by popcornmix** [comment] 2014-07-08 16:25
Can you try connecting the modem to a different linux PC (ideally running 3.12 kernel)?
That may help to narrow down where the problem is.

**Comment by ghost** [comment] 2014-07-08 17:22
Hi,
Unfortunately, for the moment, I can't, I'm on holidays and I've got (only) my Pi and a Windows PC and my Internet connection is powered by 3G (2Gb per month). I'll try when I'll be  back home,
Thank you,
Florian

**Comment by Ruffio** [comment] 2016-08-10 14:15
@ghost has this issue been resolved? If yes, then please close this issue.

**Comment by JamesH65** [comment] 2017-05-17 14:09
Closing due to lack of activity. Reopen if you feel this issue is still relevant.

**Closed as completed by JamesH65** 2017-05-17 14:09 UTC
