### ISSUE TITLE
rt3072 usb dongle causing rt2800usb_entry_txstatus_timeout errors 

### ISSUE THREAD

**Issue by wrobelda** [raspberrypi/linux#371] opened 2013-09-04 17:40 UTC
I found dmesg flooded with "phy0 -> rt2800usb_entry_txstatus_timeout: Warning - TX status timeout for entry 14 in queue" errors after updating from current to next branch today (using rpi_update). 

This appears to be a known issue, apparently fixed in fedora's kernel:
https://bugzilla.redhat.com/show_bug.cgi?id=913631

**Comment by popcornmix** [comment] 2013-09-04 21:27
If you know of an upstream patch that fixes it, I can pull it in.

**Comment by wrobelda** [comment] 2013-09-05 11:26
Can you check if the rt2800_fix_tx_power.patch that is attached to the aforementioned bug report applies cleanly? If so, I'd say this should fix this issue. 

EDIT: also discussed here: https://dev.openwrt.org/ticket/13523 
I believe no upstream report for this bug exists yet. This seems to be a fairly new bug, introduced in 3.9 series only.

**Comment by popcornmix** [comment] 2013-09-05 13:10
The response to the patch seems to be mixed at best.
It's not something I can test myself, so I'd prefer to wait for the problem to be fixed upstream, then I'm happy to cherry-pick it.

**Comment by wrobelda** [comment] 2013-09-15 21:27
Would you mind please applying some of those patches to the kernel base, compiling them and putting up for me somewhere so I can test them locally to see if any of them actually work? The amount of flood in kernel dmesg is so huge that it actually causes CPU usage of klogd and accompanying dd process of about 25% at all times when using wifi. 

I would have done this myself, but I am notorious in having little of spare time and really can't afford it these days.

My current kernel is 3.9.11+ #536, installed with rpi_update.

EDIT: never mind that, I gave up with all the issues and I'm selling my raspberry.

**Comment by bhonsalek** [comment] 2014-02-28 16:31
Any fix for this issue yet?  I am currently running Arch kernel 3.10.32-1, using an RT5370 wireless adapter set in AP mode with hostapd.  If I have high network traffic I get the floods of rt2800usb_entry_txstatus_timeout: Warning - TX status timeout and performance degrades.

**Comment by bhonsalek** [comment] 2014-03-13 20:19
Anyone???

**Comment by ghollingworth** [comment] 2014-03-13 21:42
Yes Jonathan is working on the FIQ work as we speak.  But we do not work on or support the Arch kernel, you'll need to reproduce and report under Raspbian

**Comment by Ruffio** [comment] 2016-08-10 10:52
@wrobelda has this issue been resolved? If yes, then please close this issue.

**Comment by wrobelda** [comment] 2016-08-11 23:06
I have no way of knowing - I no longer own any of these devices.

**Comment by Ruffio** [comment] 2016-08-12 04:30
@wrobelda then please close this issue as there have been no activity for two years

**Closed as completed** 2016-08-12 15:54 UTC
