### ISSUE TITLE
Serial interface sends one bit upon open() 

### ISSUE THREAD

**Issue by ACDCLabs** [raspberrypi/linux#209] opened 2013-02-02 16:50 UTC
I'm trying to set up a serial communication between the RPI and an
 FPGA. However, there is an issue when using the standard C library
 open() to init the serial interface: I'm using a scope to monitor what
 is sent and received via the RX and TX lines. A call to open causes
 the TX line of the RPI to go low for the length of one bit. I do not
 see this behavior with other computers/linux PCs. The point is, the
 FPGA assumes a valid transmission, since he thinks it's a start bit,
 but it's not.

 I checked with minicom installed on the RPI. Same thing. Starting
 minicom causes the TX line sending one bit. Once minicom has started,
 the communication runs as expected and all bytes have the correct
 frame size. Is there any way to suppress the TX line going low upon
 the open call to init the serial communication? A smart guy at
 stackoverflow suggested:

 http://stackoverflow.com/questions/14579974/init-a-serial-
 communication-with-c-library-open-causes-tx-to-send-one-bit-on-r

 Thanks 
 N.

**Comment by popcornmix** [comment] 2013-02-03 11:07
I did remove that code:
https://github.com/raspberrypi/linux/commit/316fb1932a29ca3092d264b6bd412482c169c5ff
but unfortunately it broke using the serial for console output, so that change got reverted shortly afterwards.

**Comment by popcornmix** [comment] 2013-02-20 22:00
Duplicate of:
https://github.com/raspberrypi/linux/issues/148

**Closed as completed by popcornmix** 2013-02-20 22:00 UTC

**Comment by popcornmix** [comment] 2015-02-25 21:33
Patch has been merged and is in latest rpi-update firmware.
Can you test?
