### ISSUE TITLE
Enable KVM on 64bit Builds

### ISSUE THREAD

**Issue by macromorgan** [raspberrypi/linux#3420] opened 2020-01-21 15:32 UTC
I would like to propose enabling KVM on the 64 bit builds.  To my knowledge KVM is not available for 32bit ARM, so this would require a slight deviation in the kernels between 32 and 64 bit.

I'm using KVM currently in the existing kernel (provided by sakaki- from here:  https://github.com/sakaki-/bcm2711-kernel-bis), but it would be great if I could use the actual foundation kernel which is maintained in apt for Raspbian.

**Comment by pelwell** [comment] 2020-01-21 15:56
Essentially a duplicate of #3035 (but I think you know that).

**Closed as completed by pelwell** 2020-01-21 15:56 UTC
