### ISSUE TITLE
/etc/kernel/postinst.d/apt-auto-removal not working well

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2724] opened 2018-10-17 14:00 UTC
Hello I run the raspberry as a router and need some self compiled kernel modules managed by dkms. So far so good. 
Now I see that when an kernel update is installed all modules of the current running kernel are removed, because the kernel package is removed.
apt-auto-removal create the list in /etc/apt/apt.conf.d/01autoremove-kernels but this names are different from raspbian name scheme. (for example Kernel 4.14.70 is in package raspberrypi-kernel 1.20180919-1)

Is it generally possible to install multiple kernel-packages on same time in raspbian?
So the simplest way would be to update apt-auto-removal for the right package names.

Best Regards

**Comment by XECDesign** [comment] 2018-10-17 14:24
Unfortunately, raspberrypi-kernel isn't a proper debian-style kernel package, so none of that works as intended.

**Comment by pelwell** [comment] 2018-10-29 12:22
Closing, as the question has been answered.

**Closed as completed by pelwell** 2018-10-29 12:22 UTC

**Comment by ghost** [comment] 2018-11-01 13:02
Here are 2 simple scripts. (Not tested very well).
[files.zip](https://github.com/raspberrypi/linux/files/2538577/files.zip)
