### ISSUE TITLE
when i run 

### ISSUE THREAD

**Issue by sjleesj** [raspberrypi/linux#1689] opened 2016-10-18 14:14 UTC
root@raspberrypi:/home/pi/linux-4.4.6# make modules_prepare
got   err!
CHK     include/generated/timeconst.h
/bin/sh: 1: bc: not found
Kbuild:66: recipe for target 'include/generated/timeconst.h' failed
make[1]: **\* [include/generated/timeconst.h] Error 127
Makefile:986: recipe for target 'prepare0' failed
make: **\* [prepare0] Error 2

**Comment by pelwell** [comment] 2016-10-18 14:16
Duplicate of #1685.

**Closed as completed by pelwell** 2016-10-18 14:16 UTC
