### ISSUE TITLE
Pi3 with original Display - screen stays blank after a while

### ISSUE THREAD

**Issue by moelski** [raspberrypi/linux#1747] opened 2016-12-04 19:21 UTC
Hi !

Hopefully someone here can give some advice ... I think there is something broken and maybe it´s linux kernel related ... 
I have a setup which contains Pi3 with the original 7" display (version 1.0). It worked for about one year but after the last update I have trouble. The display starts fine. And after 10 minutes it goes off - which is ok. Normally if you touch it the display it comes back. But if the Pi runs for about 1h the screen stays black. Only a reboot helps. 
If the screen is blank and I touch it I got the following error in dmesg: 
**rpi-backlight rpi_backlight: Backlight change failed**

There are other people which have this problem: 
German Forum : http://www.forum-raspberrypi.de/Thread-original-7-reagiert-nach-einiger-zeit-nicht-mehr
Englich Forum : https://www.raspberrypi.org/forums/viewtopic.php?f=108&t=154034
But no one has an answer on this issue. 

So maybe someone here can give a hint what´s wrong?

regards
  Dominik

**Comment by popcornmix** [comment] 2016-12-04 19:37
Duplicate of https://github.com/raspberrypi/linux/issues/1179

**Closed as completed by popcornmix** 2016-12-04 19:37 UTC
