### ISSUE TITLE
[RPI4] xHCI host controller not responding, assume dead

### ISSUE THREAD

**Issue by hardwareadictos** [raspberrypi/linux#3438] opened 2020-01-29 19:43 UTC
**Is this the right place for my bug report?**
This repository contains the Linux kernel used on the Raspberry Pi. If you believe that the issue you are seeing is kernel-related, this is the right place. If not, we have other repositories for the GPU firmware at [github.com/raspberrypi/firmware](https://github.com/raspberrypi/firmware) and Raspberry Pi userland applications at [github.com/raspberrypi/userland](https://github.com/raspberrypi/userland). If you have problems with the Raspbian distribution packages, report them in the [github.com/RPi-Distro/repo](https://github.com/RPi-Distro/repo). If you simply have a question, then [the Raspberry Pi forums](https://www.raspberrypi.org/forums) are the best place to ask it.

**Describe the bug**
Randomly all HDDs connected to Raspberry Pi 4 gets disconnected.

**To reproduce**
Theres not a concrete action to reproduce it. Its happening randomly.

**Expected behaviour**
Disks should be stable not disappearing constantly from system.

**Actual behaviour**
Disks randomly being disconnected.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi?  
Pi4
* Which OS and version (`cat /etc/rpi-issue`)?
Raspberry Pi reference 2019-09-26
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 80d486687ea77d31fc3fc13cf3a2f8b464e129be, stage2
* Which firmware version (`vcgencmd version`)?
Jan 10 2020 16:52:04
Copyright (c) 2012 Broadcom
version fdb5c37e330e7cb3027ac4fcc5b1cd5f244b351f (clean) (release) (start)
* Which kernel version (`uname -a`)?
Linux CrypticGraciel-RPI02 4.19.93-v7l+ #1290 SMP Fri Jan 10 16:45:11 GMT 2020 armv7l GNU/Linux

**Logs**
Attatched

**Additional context**
Just using one SSD conected to a Suptronic X825 and one External HDD. Both connected to 3.0 ports. Tried plugging external one to 2.0 to avoid any bus issue, no luck.

dmesg:

[log_xhci_rpi4.txt](https://github.com/raspberrypi/linux/files/4130379/log_xhci_rpi4.txt)

**Comment by P33M** [comment] 2020-01-30 21:32
Duplicate of #3404

**Closed as completed by P33M** 2020-01-30 21:32 UTC
